Update plan-for-software-updates.md
MicrosoftDocs/memdocs pull request #1673
Opened 2021-06-04 21:23 UTC by rashid2982

Added below portion under SSU/CU install logic.

<mark>If you have non-windows updates like office or 3rd party on the same deadline and they require reboot after install, CU might not install right after SSU because machine required a reboot before doing a full scan again, This can achieved by using the checkbox in the deployment settings "If any update in this deployment requires a system restart, run update deployment evaluation cycle after restart".</mark>

2021-06-04 21:24 UTC, PRMerger6 commented
@rashid2982 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-06-04 21:44 UTC, v-andreaco commented
If approved, this content might benefit from a grammar pass before being merged.

Also, please remove the html `<mark>` - it can be changed to a Markdown note, tip, or important.

2021-09-01 17:12 UTC, ktoliver commented
@mestew @aczechowski Would one of you be able to review the proposed update? Thanks.

2021-11-29 16:33 UTC, Jak-MS commented
nudge @mestew @aczechowski .  Would one of you be able to review the proposed update? Thanks.

2023-01-29 06:08 UTC, JohanFreelancer9 commented on memdocs/configmgr/sum/plan-design/plan-for-software-updates.md
> +<mark>If you have non-windows updates like office or 3rd party on the same deadline and they require reboot after install, CU might not install right after SSU because machine required a reboot befor
```suggestion
<mark>If you have non-Windows updates like Office or third-party updates on the same deadline and they require a restart after installation, cumulative updates might not install right after the SSU because the computer required a restart before doing a full scan again, This can be achieved by selecting the **If any update in this deployment requires a system restart, run update deployment evaluation cycle after restart** checkbox in deployment settings.</mark>
```

2023-01-29 06:09 UTC, JohanFreelancer9 requested changes
Copy review - this PR is quite old. I am not sure if it is still relevant.

2024-06-20 05:15 UTC, dougeby commented
Updates look good. Merging.

2024-06-20 05:16 UTC, merged