Update intune-endpoints.md
MicrosoftDocs/memdocs pull request #2479
Opened 2022-02-25 07:49 UTC by msbemba

Added related topics per request

2022-02-25 07:49 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-02-25 07:49 UTC, PRMerger8 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-02-25 07:49 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/1272

2022-02-25 09:41 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/intune-endpoints.md
> +
```suggestion
[Office 365 URLs and IP address ranges](/microsoft-365/enterprise/urls-and-ip-address-ranges)

[Microsoft 365 network connectivity overview](https://support.office.com/article/client-connectivity-4232abcf-4ae5-43aa-bfa1-9a078a99c78b)

[Content delivery networks (CDNs)](https://support.office.com/article/content-delivery-networks-0140f704-6614-49bb-aa6c-89b75dcd7f1f)

[Other endpoints not included in the Office 365 IP Address and URL Web service](/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls)

[Managing Office 365 endpoints](/microsoft-365/enterprise/managing-office-365-endpoints)
```

2022-02-25 09:42 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-25 11:06 UTC, PRMerger12 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-02-25 11:24 UTC, JohanFreelancer9 approved these changes

2022-02-27 10:06 UTC, yogkumgit commented
@Smritib17 Please review and merge this PR. Thanks

2022-03-03 13:24 UTC, yogkumgit commented
@Smritib17 Gentle reminder

2022-03-17 16:17 UTC, Smritib17 approved these changes

2022-03-17 16:17 UTC, Smritib17 commented
#sign-off

2022-03-17 16:17 UTC, merged