Update apps-advanced-threat-protection-macos.md
MicrosoftDocs/memdocs pull request #2486
Opened 2022-02-25 14:38 UTC by msbemba

Added information about Intune-based deployment for Microsoft Defender for Endpoint on macOS to the next steps

2022-02-25 14:38 UTC, PRMerger20 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-02-27 10:41 UTC, yogkumgit commented
@JohanFreelancer9 copy review

2022-02-28 04:47 UTC, JohanFreelancer9 commented on memdocs/intune/apps/apps-advanced-threat-protection-macos.md
> +- To learn about Intune-based deployment for Microsoft Defender for Endpoint on macOS, see [Intune-based deployment for MDE on macOS](/microsoft-365/security/defender-endpoint/mac-install-with-intune
```suggestion
- To learn about Intune-based deployment for Microsoft Defender for Endpoint on macOS, see [Intune-based deployment for Microsoft Defender for Endpoint on macOS](/microsoft-365/security/defender-endpoint/mac-install-with-intune)
```

2022-02-28 04:48 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-28 05:49 UTC, PRMerger12 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-02-28 06:04 UTC, JohanFreelancer9 approved these changes

2022-02-28 10:44 UTC, yogkumgit commented
@Erikre Please review and merge this PR. Thanks

2022-03-31 13:55 UTC, yogkumgit commented
@Erikre Gentle reminder. Thanks

2022-04-04 23:36 UTC, merged