Update data-transfer-between-apps-manage-ios.md
MicrosoftDocs/memdocs pull request #2488
Opened 2022-02-25 15:02 UTC by msbemba

Updated the note as adding app configuration key to the receiving app is still optional.

2022-02-25 15:03 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/1447

2022-02-25 15:03 UTC, PRMerger4 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-02-25 15:04 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-02-25 15:35 UTC, JohanFreelancer9 commented on memdocs/intune/apps/data-transfer-between-apps-manage-ios.md
> +     > Deploy IntuneMAMUPN app configuration settings to the target managed app which sends data, adding the app configuration key to the receiving app is optional.
```suggestion
     > Deploy IntuneMAMUPN app configuration settings to the target managed app which sends data. Adding the app configuration key to the receiving app is optional. 
```

2022-02-25 15:35 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-25 17:17 UTC, PRMerger14 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-02-27 10:21 UTC, yogkumgit commented
@JohanFreelancer9

2022-02-28 05:11 UTC, JohanFreelancer9 approved these changes

2022-02-28 10:45 UTC, yogkumgit commented
@Erikre Please review and merge this PR. Thanks

2022-03-01 06:19 UTC, Erikre approved these changes

2022-03-01 06:19 UTC, Erikre commented
#sign-off

2022-03-01 12:40 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-03-01 20:07 UTC, merged