Update end-user-mam-apps-ios.md
MicrosoftDocs/memdocs pull request #2491
Opened 2022-02-26 09:17 UTC by msbemba

Added a section for required approved client app

2022-02-26 09:17 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-02-26 09:17 UTC, PRMerger18 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-02-26 09:17 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/1357

2022-02-27 04:49 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/end-user-mam-apps-ios.md
> +### Require approved client app
```suggestion
### Approved client app requirement
```

2022-02-27 04:50 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/end-user-mam-apps-ios.md
> +Organizations can require that an access attempt to the selected cloud apps needs to be made from an approved client app. These approved client apps support [Intune app protection policies](/intune/a
```suggestion
Organizations might require that an access attempt to the selected cloud apps needs to be made from an approved client app. These approved client apps support [Intune app protection policies](/intune/app-protection-policy) independent of any mobile device management (MDM) solution.
```

2022-02-27 04:55 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/end-user-mam-apps-ios.md
> +In order to apply this grant control, Conditional Access requires that the device is registered in Azure Active Directory, which requires the use of a broker app. The broker app can be the Microsoft
```suggestion
In order to apply this grant control, Conditional Access requires that the device is registered in Azure Active Directory, which requires the use of a broker app. The broker app could be the Microsoft Authenticator for iOS. If a broker app isn’t installed on the device when the user attempts to authenticate, the user gets redirected to the appropriate app store to install the required broker app.
```

2022-02-27 04:57 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-27 05:34 UTC, PRMerger7 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-02-27 05:34 UTC, PRMerger8 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-02-27 05:36 UTC, JohanFreelancer9 approved these changes

2022-02-27 10:13 UTC, yogkumgit commented
@lenewsad Please review and merge this PR. Thanks

2022-03-01 18:23 UTC, lenewsad commented
#sign-off

2022-03-03 13:16 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-03-03 16:41 UTC, merged