Update apps-selective-wipe.md
MicrosoftDocs/memdocs pull request #2510
Opened 2022-03-04 13:34 UTC by msbemba

Made changes to the line about selective data to reduce ambiguity

2022-03-04 13:34 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-04 13:35 UTC, PRMerger-2 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-04 13:35 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/1960

2022-03-04 15:03 UTC, JohanFreelancer9 commented on memdocs/intune/apps/apps-selective-wipe.md
> +To selectively remove company app data, create a wipe request by using the steps in this topic. After the request is finished, the next time the app runs on the device, company data is removed from t
```suggestion
To selectively remove company app data, create a wipe request by using the steps in this topic. After the request is finished, the next time the app runs on the device, company data is removed from the app. In addition, you can also configure a selective wipe of your company data as a new action when the conditions of Application Protection Policies (APP) Access settings are not met. This feature helps you automatically protect and remove sensitive company data from applications based on pre-configured criteria.
```

2022-03-04 15:03 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-04 15:48 UTC, PRMerger9 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-05 05:22 UTC, JohanFreelancer9 approved these changes

2022-03-05 07:57 UTC, yogkumgit commented
@Erikre Please review and merge this PR. Thanks

2022-04-04 23:29 UTC, merged