Update apps-add-built-in.md
MicrosoftDocs/memdocs pull request #2519
Opened 2022-03-05 22:19 UTC by msbemba

Checked and found the built-in apps consists of m365 apps as well as third party apps.

2022-03-05 22:19 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-05 22:19 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/memdocs/issues/1650

2022-03-05 22:19 UTC, PRMerger20 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-07 04:24 UTC, JohanFreelancer9 commented on memdocs/intune/apps/apps-add-built-in.md
> +The *built-in* app type makes it easy for you to assign curated managed apps, such as Microsoft 365 apps and third party apps, to iOS/iPadOS and Android devices. You can assign specific apps for this
```suggestion
The *built-in* app type makes it easy for you to assign curated managed apps, such as Microsoft 365 apps and third-party apps, to iOS/iPadOS and Android devices. You can assign specific apps for this app type, such as Excel, OneDrive, Outlook, Skype, and others. After you add an app, the app type is displayed as either *Built-in iOS app* or *Built-in Android app*. By using the built-in app type, you can choose which of these apps to publish to device users.
```

2022-03-07 04:24 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-07 06:11 UTC, PRMerger16 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-07 08:10 UTC, JohanFreelancer9 approved these changes

2022-03-08 03:12 UTC, yogkumgit commented
@Erikre Please review and merge this PR. Thanks

2022-05-02 20:02 UTC, Erikre approved these changes

2022-05-02 20:02 UTC, Erikre commented
#sign-off

2022-05-03 11:12 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-05-03 19:54 UTC, merged