Update corporate-identifiers-add.md
MicrosoftDocs/memdocs pull request #2524
Opened 2022-03-05 22:49 UTC by msbemba

Added Android Enterprise corporate-owned devices to the list of automatically assigned corporate-owned status in intune

2022-03-05 22:49 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/1710

2022-03-05 22:49 UTC, msbemba commented
@JohanFreelancer9 please copy review

2022-03-05 22:49 UTC, PRMerger8 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-07 05:07 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/corporate-identifiers-add.md
> +- Enrolled with [Android Enterprise corporate-owned devices with work profile](/mem/intune/enrollment/android-corporate-owned-work-profile-enroll).
```suggestion
- Enrolled with [Android Enterprise corporate-owned devices with work profile](/mem/intune/enrollment/android-corporate-owned-work-profile-enroll)
```

2022-03-07 05:07 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-07 06:11 UTC, PRMerger8 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-07 08:09 UTC, JohanFreelancer9 approved these changes

2022-03-08 03:17 UTC, yogkumgit commented
@lenewsad Please review and merge this PR. Thanks

2022-03-31 14:01 UTC, yogkumgit commented
@lenewsad Gentle reminder. Thanks

2022-03-31 21:18 UTC, PRMerger20 commented
@lenewsad : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-31 21:22 UTC, lenewsad commented
#sign-off

2022-04-01 11:58 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-04-01 12:58 UTC, merged