Update create-conditional-access-intune.md
MicrosoftDocs/memdocs pull request #2527
Opened 2022-03-05 23:10 UTC by msbemba

Added permissions required to perform the action

2022-03-05 23:10 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-05 23:10 UTC, PRMerger18 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-05 23:10 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/1870

2022-03-07 05:38 UTC, JohanFreelancer9 commented on memdocs/intune/protect/create-conditional-access-intune.md
> +Conditional Access Administrator
```suggestion
    - Global administrator	
    - Intune Service administrator	
    - Conditional Access administrator	
```

2022-03-07 05:40 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-07 06:10 UTC, PRMerger16 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-07 07:57 UTC, JohanFreelancer9 approved these changes

2022-03-07 14:44 UTC, Brenduns commented
#sign-off

2022-03-08 03:22 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-03-08 17:54 UTC, merged

2022-03-08 19:01 UTC, Brenduns commented
@yogkumgit @tiburd   Question: This edit ended up introducing a warning for the main branch during daily publishing. It turns out the edits for bullet points that start on line 39 are indented and should not be.  I didn't see a build report when this came in (Still don't see it in this web view) so I didn't notice that.  But when the PR was submitted, that type of build issue should have been flagged. 

Did either of you see a build report showing the indent problem when this submission was first made?  

I'll review future edits more closely if the PR's don't show me a build report! :)

2022-03-08 20:01 UTC, tiburd commented
@Brenduns 
Hi, Brent,
I don't think we see build reports for public repo PRs...
Thanks!

@msbemba @JohanFreelancer9 
Please note Brent's comment above regarding not indenting bullets in Markdown.
Thanks!

2022-03-09 10:42 UTC, msbemba commented
Thank you @tiburd. I will make a note.