Update device-limit-intune-azure.md
MicrosoftDocs/memdocs pull request #2544
Opened 2022-03-13 17:56 UTC by msbemba

Updated the document to remove the conflicting information.

Reference -https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-program-enroll-ios

user affinity is supported in  iOS/macOS ADE

2022-03-13 17:56 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/memdocs/issues/2031

2022-03-13 17:57 UTC, PRMerger4 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-13 17:57 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-14 05:10 UTC, JohanFreelancer9 approved these changes

2022-03-14 13:01 UTC, yogkumgit commented
@lenewsad Please review and merge this PR. Thanks

2022-03-24 16:28 UTC, yogkumgit commented
@lenewsad Gentle reminder, Please merge this PR. Thanks

2022-04-01 15:37 UTC, lenewsad approved these changes

2022-04-01 15:38 UTC, lenewsad commented
Thanks @msbemba! Made some minor changes to fix table formatting. 

#sign-off

2022-04-02 04:31 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/device-limit-intune-azure.md
> +| ----- | ----- | ----- | ----- | ----- |
```suggestion
| ----- | ----- | ----- | ----- |
```

2022-04-02 04:32 UTC, JohanFreelancer9 requested changes
@msbemba, the table does not render correctly. Committing this suggested change should fix it. Thanks.

2022-04-02 12:29 UTC, yogkumgit commented
@msbemba

2022-04-03 17:04 UTC, PRMerger-2 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-04 01:13 UTC, JohanFreelancer9 approved these changes

2022-04-04 15:19 UTC, merged