Update intune-notices.md
MicrosoftDocs/memdocs pull request #2547
Opened 2022-03-13 19:08 UTC by msbemba

Updated the document to state  " Apple has released iOS 15. Microsoft Intune, including the Intune Company Portal and Intune app protection policies (APP, also known as mobile application management), will require  iOS/iPadOS 13 and later." as this content is included in other documents such as  fundamentals/whats-new.md and fundamentals/in-development.md

2022-03-13 19:08 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/memdocs/issues/2056

2022-03-13 19:08 UTC, PRMerger13 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-13 19:08 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-14 04:36 UTC, JohanFreelancer9 commented on memdocs/intune/includes/intune-notices.md
> +Apple has released iOS 15. Microsoft Intune, including the Intune Company Portal and Intune app protection policies (APP, also known as mobile application management), will require  iOS/iPadOS 13 and
```suggestion
Apple has released iOS 15. Microsoft Intune, including Intune Company Portal and Intune app protection policies (APP, also known as mobile application management), require iOS/iPadOS 13 and later.
```

2022-03-14 04:36 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-14 09:10 UTC, PRMerger20 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-14 13:08 UTC, yogkumgit commented
@ErikjeMS Please review and merge this PR. Thanks

2022-03-15 06:41 UTC, JohanFreelancer9 approved these changes

2022-03-24 16:30 UTC, yogkumgit commented
@dougeby Gentle reminder, Please merge this PR. Thanks

2022-03-25 05:56 UTC, PRMerger9 commented
@dougeby : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-25 05:57 UTC, merged