Update app-protection-policy-settings-android.md
MicrosoftDocs/memdocs pull request #2554
Opened 2022-03-15 14:52 UTC by msbemba

Updated the document with Box as it is now available as an option to Allow user to save copies to selected services'

2022-03-15 14:52 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-15 14:52 UTC, PRMerger18 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-15 14:53 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2144

2022-03-16 06:25 UTC, yogkumgit commented
@Erikre Please merge this PR. Thanks

2022-03-16 09:30 UTC, JohanFreelancer9 commented on memdocs/intune/apps/app-protection-policy-settings-android.md
> +|<ul><b><ul><b>**Allow user to save copies to selected services** |Users can save to the selected services (OneDrive for Business, SharePoint, Box and Local Storage). All other services will be block
```suggestion
|<ul><b><ul><b>**Allow user to save copies to selected services** |Users can save to the selected services (OneDrive for Business, SharePoint, Box, and Local Storage). All other services will be blocked.  | **0 selected** |
```

2022-03-16 09:30 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-16 12:12 UTC, PRMerger15 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-16 18:18 UTC, JohanFreelancer9 approved these changes

2022-04-04 23:14 UTC, merged