Update make-configmgr-collection-available-edr.md
MicrosoftDocs/memdocs pull request #2557
Opened 2022-03-15 16:03 UTC by msbemba

Updated step 3 to add AAD group

2022-03-15 16:03 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-15 20:32 UTC, Brenduns commented
#sign-off

2022-03-16 06:02 UTC, yogkumgit commented
@Brenduns When you sign off then please either merge the PR or leave it as it is so that @tiburd can procced to merge. Please close the PR only if you disagree and do not want the changes to be reflected in the document Tina your comment please.

2022-03-16 10:05 UTC, JohanFreelancer9 commented on memdocs/intune/protect/includes/make-configmgr-collection-available-edr.md
> +3. Click on **Add** and **Select** the Azure Active Diretiry group that you would like to syncrhonize Collect memberhsip results with.
```suggestion
3. Select **Add** and then select the Azure Active Directory group that you would like to synchronize with _Collect membership results_.
```

2022-03-16 10:06 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-16 10:08 UTC, PRMerger7 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-16 10:11 UTC, JohanFreelancer9 approved these changes

2022-03-16 16:07 UTC, tiburd commented
> @Brenduns When you sign off then please either merge the PR or leave it as it is so that @tiburd can procced to merge. Please close the PR only if you disagree and do not want the changes to be reflected in the document Tina your comment please.

Yes, that is how the process usually works. 
Brent, thank you for reviewing and approving the proposed changes. You're welcome to contact me if you have any questions about the process. 
Thanks!

2022-03-16 16:07 UTC, merged