Update app-configuration-managed-home-screen-app.md
MicrosoftDocs/memdocs pull request #2561
Opened 2022-03-16 04:21 UTC by chmaguir

update to doc

2022-03-16 04:21 UTC, PRMerger17 commented
@chmaguir : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-17 04:36 UTC, JohanFreelancer9 commented on memdocs/intune/apps/app-configuration-managed-home-screen-app.md
> +| Show device's name on MHS | bool | FALSE | Turn this setting to True to easily view the device's Intune portal "device name" property from the Managed Settings app or from swipe-down when **Show de
```suggestion
| Show device's name on MHS | bool | FALSE | Turn this setting to True to easily view the device's Intune portal "device name" property from the Managed Settings app or from swipe-down when **Show device info setting** is set to True. Make sure to also include the string property "Device's name," which is auto-populated by Intune with the correct value. | ❌ |
```

2022-04-17 04:38 UTC, JohanFreelancer9 commented on memdocs/intune/apps/app-configuration-managed-home-screen-app.md
> +| Show serial number for all supported OS version on MHS | choice | {{serialnumber}} | Ensure that in app config device_serial_number is configured to display {{SerialNumber}} **Show device info sett
```suggestion
| Show serial number for all supported OS version on MHS | choice | {{serialnumber}} | Ensure that in-app config device_serial_number is configured to display {{SerialNumber}} and **Show device info setting** is set to True. This value is auto-populated by Intune with the correct value. | ❌ |
```

2022-04-17 04:43 UTC, JohanFreelancer9 requested changes
Copy review - @chmaguir, kindly commit the minor suggested changes. Many thanks.

2022-04-19 16:45 UTC, Erikre approved these changes

2022-04-19 16:45 UTC, Erikre commented
#sign-off

2022-04-20 05:26 UTC, yogkumgit commented
@chmaguir Please implement the suggested changes. Thanks

2022-04-25 16:14 UTC, PRMerger19 commented
@Erikre : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-25 16:15 UTC, Erikre approved these changes

2022-04-25 16:16 UTC, Erikre commented
#sign-off

2022-04-26 07:38 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-04-26 13:01 UTC, merged

2022-04-26 13:01 UTC, PRMerger4 commented
@tiburd : Thanks for your contribution! The author(s) have been notified to review your proposed change.