Update windows-autopilot-hybrid.md
MicrosoftDocs/memdocs pull request #2591
Opened 2022-03-24 11:28 UTC by msbemba

Updated the document as the navigation has changed

2022-03-24 11:28 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2253

2022-03-24 11:28 UTC, PRMerger20 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-24 11:29 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-25 03:23 UTC, JohanFreelancer9 commented on memdocs/autopilot/windows-autopilot-hybrid.md
> +    - **Profile type**: Select **Tempplates**, Choose the Template name **Domain Join** and click on **Create**
```suggestion
    - **Profile type**: Select **Templates**, choose the template name **Domain Join** and select **Create**.
```

2022-03-25 03:24 UTC, JohanFreelancer9 commented on memdocs/autopilot/windows-autopilot-hybrid.md
> +3. Enter the **Name**, **Description** and Click on **Next**
```suggestion
3. Enter the **Name** and **Description** and select **Next**. 
```

2022-03-25 03:25 UTC, JohanFreelancer9 commented on memdocs/autopilot/windows-autopilot-hybrid.md
> +5. Provide a **Computer name prefix**, **Domain name**.
```suggestion
5. Provide a **Computer name prefix** and **Domain name**.
```

2022-03-25 03:27 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-25 04:29 UTC, PRMerger14 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-25 04:29 UTC, PRMerger16 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-25 11:31 UTC, JohanFreelancer9 approved these changes

2022-03-31 14:14 UTC, yogkumgit commented
@dougeby Kindly help. Thanks

2022-04-04 23:03 UTC, merged