Update apps-win32-supersedence.md
MicrosoftDocs/memdocs pull request #2592
Opened 2022-03-24 11:56 UTC by msbemba

Updated the document to reflect the the company portal shows only the superseding app.

2022-03-24 11:56 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-24 11:56 UTC, PRMerger20 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-24 11:56 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2265

2022-03-25 03:29 UTC, JohanFreelancer9 commented on memdocs/intune/apps/apps-win32-supersedence.md
> +| **Scenario   1:**<br> The superseded app exists on the device and **Uninstall previous version** is set to **Yes**. | The superseded app will be   uninstalled, and the superseding app will be insta
```suggestion
| **Scenario   1:**<br> The superseded app exists on the device and **Uninstall previous version** is set to **Yes**. | The superseded app will be uninstalled, and the superseding app will be installed on the device.<p> **NOTE:** Even if the superseded app is not targeted, it will be uninstalled. | Only Superseding apps will be shown in the company portal and can be installed. |
```

2022-03-25 03:32 UTC, JohanFreelancer9 commented on memdocs/intune/apps/apps-win32-supersedence.md
> +| **Scenario   2:**<br>The superseded app exists on the device and **Uninstall   previous version** is set to **No**. | The superseding app will be   installed on the device. Whether the superseded a
```suggestion
| **Scenario   2:**<br>The superseded app exists on the device and **Uninstall previous version** is set to **No**. | The superseding app will be installed on the device. Whether the superseded app will be uninstalled or not is dependent on the superseding app’s installer. | Only Superseding apps will be shown in the company portal and can be installed. |
```

2022-03-25 03:36 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-25 04:29 UTC, PRMerger8 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-25 11:50 UTC, JohanFreelancer9 approved these changes

2022-03-25 13:54 UTC, yogkumgit commented
@Erikre Please review and merge this PR. Thanks

2022-03-31 14:12 UTC, yogkumgit commented
@Erikre Gentle reminder. Thanks

2022-05-02 20:21 UTC, Erikre approved these changes

2022-05-02 20:21 UTC, Erikre commented
#sign-off

2022-05-03 11:21 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-05-03 19:56 UTC, merged