Update windows-autopilot-hybrid.md
MicrosoftDocs/memdocs pull request #2625
Opened 2022-04-04 14:27 UTC by msbemba

Updated the document to reflect that the rule syntax needs to be edited (options have changed)

2022-04-04 14:27 UTC, PRMerger15 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-04 14:27 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-04-05 04:54 UTC, JohanFreelancer9 commented on memdocs/autopilot/windows-autopilot-hybrid.md
> +5. Click on **Edit** in the **Rule syntax** box, enter one of the following code lines:
```suggestion
5. Select **Edit** in the **Rule syntax** box and enter one of the following code lines:
```

2022-04-05 04:55 UTC, JohanFreelancer9 commented on memdocs/autopilot/windows-autopilot-hybrid.md
>      - Intune's Group Tag field maps to the OrderID attribute on Azure AD devices. If you want to create a group that includes all of your Autopilot devices with a specific Group Tag(OrderID), type: `
```suggestion
    - Intune's Group Tag field maps to the OrderID attribute on Azure AD devices. If you want to create a group that includes all of your Autopilot devices with a specific Group Tag (OrderID), type: `(device.devicePhysicalIds -any _ -eq "[OrderID]:179887111881")`.
```

2022-04-05 04:55 UTC, JohanFreelancer9 requested changes
Copy review.

2022-04-05 06:05 UTC, PRMerger-2 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-05 10:07 UTC, JohanFreelancer9 approved these changes

2022-04-05 13:29 UTC, yogkumgit commented
@dougeby Please merge this PR. Thanks

2022-04-19 02:16 UTC, merged