Update conditional-access-integrate-jamf.md
MicrosoftDocs/memdocs pull request #2626
Opened 2022-04-04 14:56 UTC by msbemba

Made changes to the document as per the new Jamf pro navigation changes

Reference -https://docs.jamf.com/technical-papers/jamf-pro/microsoft-intune/10.34.0/Manually_Configure_the_Connection_Between_Jamf_Pro_and_Microsoft_Intune.html

2022-04-04 14:56 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-04-04 14:56 UTC, PRMerger5 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-04 14:56 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2377

2022-04-05 05:02 UTC, JohanFreelancer9 commented on memdocs/intune/protect/conditional-access-integrate-jamf.md
> +- Global Administrator role in Azure Active Directory.
```suggestion
- Global admin role in Azure Active Directory.
```

2022-04-05 05:03 UTC, JohanFreelancer9 commented on memdocs/intune/protect/conditional-access-integrate-jamf.md
> +10. Under **Microsoft Graph**, click **Application permissions**, and then select **Application.Read.All**.
```suggestion
10. Under **Microsoft Graph**, select **Application permissions**, then select **Application.Read.All**.
```

2022-04-05 05:03 UTC, JohanFreelancer9 commented on memdocs/intune/protect/conditional-access-integrate-jamf.md
> +11. Click **Add permissions**.
```suggestion
11. Select **Add permissions**.
```

2022-04-05 05:05 UTC, JohanFreelancer9 commented on memdocs/intune/protect/conditional-access-integrate-jamf.md
> +12. Navigate to APIs my organization uses. Search for and click **Windows Azure Active Directory**. Click **Application permissions**, and then select **Application.Read.All**.
```suggestion
12. Navigate to **APIs my organization uses**. Search for and select **Windows Azure Active Directory**. Select **Application permissions**, and then select **Application.Read.All**.
```

2022-04-05 05:05 UTC, JohanFreelancer9 commented on memdocs/intune/protect/conditional-access-integrate-jamf.md
> +13. Click **Add permissions**.
```suggestion
13. Select **Add permissions**.
```

2022-04-05 05:07 UTC, JohanFreelancer9 commented on memdocs/intune/protect/conditional-access-integrate-jamf.md
> +15. Refresh the page by click on the **Refresh** button at the top of the page. Confirm that admin consent has been granted for the **update_device_attributes** permission.
```suggestion
15. Refresh the page by selecting **Refresh** at the top of the page. Confirm that admin consent has been granted for the **update_device_attributes** permission. 
```

2022-04-05 05:08 UTC, JohanFreelancer9 commented on memdocs/intune/protect/conditional-access-integrate-jamf.md
>     1. Open the Jamf Pro console and navigate to **Global Management** > **Conditional Access**. Click the **Edit** button on the **macOS Intune Integration** tab.
```suggestion
   1. Open the Jamf Pro console and navigate to **Global Management** > **Conditional Access**. Select **Edit** on the **macOS Intune Integration** tab.
```

2022-04-05 05:11 UTC, JohanFreelancer9 commented on memdocs/intune/protect/conditional-access-integrate-jamf.md
> +   3. Select **Manua** under Connection Type.
```suggestion
   3. Select **Manual** under **Connection type**.
```

2022-04-05 05:12 UTC, JohanFreelancer9 commented on memdocs/intune/protect/conditional-access-integrate-jamf.md
> +   5. Click **Open administrator consent URL**, and follow the onscreen instructions to allow the Jamf Native macOS Connector app to be added to your Azure AD tenant.
```suggestion
   5. Select **Open administrator consent URL** and follow the onscreen instructions to allow the Jamf Native macOS Connector app to be added to your Azure AD tenant.
```

2022-04-05 05:14 UTC, JohanFreelancer9 requested changes
Copy review.

2022-04-05 06:03 UTC, PRMerger6 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-05 06:03 UTC, PRMerger9 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-05 06:03 UTC, PRMerger10 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-05 06:03 UTC, PRMerger17 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-05 06:03 UTC, PRMerger18 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-05 06:04 UTC, PRMerger-2 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-05 06:04 UTC, PRMerger7 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-05 09:57 UTC, JohanFreelancer9 approved these changes

2022-04-05 15:41 UTC, merged