Update lob-apps-macos-dmg.md
MicrosoftDocs/memdocs pull request #2632
Opened 2022-04-05 07:41 UTC by msbemba

Added details about error 0x87D3013A

2022-04-05 07:41 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-04-05 07:41 UTC, PRMerger16 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-05 07:41 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2395

2022-04-05 10:25 UTC, JohanFreelancer9 commented on memdocs/intune/apps/lob-apps-macos-dmg.md
> +| 0x87D3013A | The physical resources of this disk have been exhausted. | This could be due to hard disk running out of space or binaries  of the installation files are corrupt. Fix the Hard disk spa
```suggestion
| 0x87D3013A | The physical resources of this disk have been exhausted. | This could be due to the hard disk running out of space or binaries of the installation files being corrupt. Fix the Hard disk space and restart the Microsoft Intune Management Extension service and try again. |
```

2022-04-05 10:26 UTC, JohanFreelancer9 requested changes
Copy review.

2022-04-05 12:05 UTC, PRMerger6 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-06 01:29 UTC, JohanFreelancer9 approved these changes

2022-04-07 03:28 UTC, yogkumgit commented
@Erikre Please merge this PR. Thanks

2022-05-02 20:21 UTC, Erikre approved these changes

2022-05-02 20:22 UTC, Erikre commented
#sign-off

2022-05-03 11:22 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-05-03 19:56 UTC, merged