Update windows-autopilot-hybrid.md
MicrosoftDocs/memdocs pull request #2633
Opened 2022-04-05 07:49 UTC by msbemba

Made changes to the navigation as the document just  states Profile type: Select Domain Join.

2022-04-05 07:50 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/memdocs/issues/2422

2022-04-05 07:50 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-04-05 10:32 UTC, JohanFreelancer9 commented on memdocs/autopilot/windows-autopilot-hybrid.md
> +    - **Profile type**: Choose **Templates**, Select the template name **Domain Join** and click on **Create**.
```suggestion
    - **Profile type**: Select**Templates**, choose the template name **Domain Join**, and select **Create**.
```

2022-04-05 10:39 UTC, JohanFreelancer9 requested changes
Copy review.

2022-04-05 12:05 UTC, PRMerger-2 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-06 01:19 UTC, JohanFreelancer9 approved these changes

2022-04-07 03:29 UTC, yogkumgit commented
@greg-lindsay Please merge this PR. Thanks

2022-04-19 02:21 UTC, PRMerger8 commented
@dougeby : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-19 02:22 UTC, merged