Update android-deployment-scenarios-app-protection-work-profiles.md
MicrosoftDocs/memdocs pull request #2635
Opened 2022-04-05 08:25 UTC by msbemba

Removed contradicting statement as intune support two scenarios for BYOD

2022-04-05 08:26 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-04-05 08:26 UTC, PRMerger-2 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-05 08:26 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/memdocs/issues/2436

2022-04-05 10:53 UTC, JohanFreelancer9 commented on memdocs/intune/apps/android-deployment-scenarios-app-protection-work-profiles.md
> +Android Enterprise personally-owned work profiles is the core Android Enterprise deployment scenario . The Android Enterprise personally-owned work profile is a separate partition created at the Andr
```suggestion
Android Enterprise personally-owned work profiles are the core Android Enterprise deployment scenario. The Android Enterprise personally-owned work profile is a separate partition created at the Android OS level that can be managed by Intune.
```

2022-04-05 10:54 UTC, JohanFreelancer9 requested changes
Copy review.

2022-04-05 12:04 UTC, PRMerger17 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-06 01:08 UTC, JohanFreelancer9 approved these changes

2022-04-07 03:33 UTC, yogkumgit commented
@Erikre Please merge this PR. Thanks

2022-05-02 20:22 UTC, Erikre approved these changes

2022-05-02 20:22 UTC, Erikre commented
#sign-off

2022-05-03 11:24 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-05-03 19:57 UTC, merged