Update app-discovered-apps.md
MicrosoftDocs/memdocs pull request #2640
Opened 2022-04-06 07:40 UTC by msbemba

reduced ambiguity by correcting descriptions for For company-owned devices	(Android enterprise)

2022-04-06 07:40 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-04-06 07:40 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2445

2022-04-06 07:40 UTC, PRMerger6 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-06 10:35 UTC, JohanFreelancer9 commented on memdocs/intune/apps/app-discovered-apps.md
> +| Android Enterprise | Only managed apps | Only apps installed in the Android Enterprise work profile device | Every 7 days from device enrollment |
```suggestion
| Android Enterprise | Only managed apps | Only apps installed on the Android Enterprise work profile device | Every 7 days from device enrollment |
```

2022-04-06 10:35 UTC, JohanFreelancer9 requested changes
Copy review.

2022-04-06 12:05 UTC, PRMerger12 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-07 03:35 UTC, yogkumgit commented
@JohanFreelancer9

2022-04-07 03:36 UTC, yogkumgit commented
@Erikre Please merge this PR. Thanks

2022-04-07 06:30 UTC, JohanFreelancer9 approved these changes

2022-05-02 20:23 UTC, Erikre approved these changes

2022-05-02 20:23 UTC, Erikre commented
#sign-off

2022-05-02 20:23 UTC, Erikre approved these changes

2022-05-03 11:24 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-05-03 19:57 UTC, merged