Update ios-ipados-supervised-device-security-configurations.md
MicrosoftDocs/memdocs pull request #2668
Opened 2022-04-11 12:00 UTC by msbemba

Made changes to the Level 2 verbiage

2022-04-11 12:00 UTC, PRMerger13 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-11 12:01 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2513

2022-04-16 03:59 UTC, yogkumgit commented
@JohanFreelancer9

2022-04-16 05:59 UTC, JohanFreelancer9 approved these changes

2022-04-18 17:43 UTC, lenewsad approved these changes

2022-04-18 17:43 UTC, lenewsad commented
#sign-off

2022-04-19 04:13 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/ios-ipados-supervised-device-security-configurations.md
> +Level 2 is the recommended configuration for supervised  devices where users access more sensitive information. These devices are a natural target in enterprises today. These settings don't assume a
```suggestion
Level 2 is the recommended configuration for supervised devices where users access more sensitive information. These devices are a natural target in enterprises today. These settings don't assume a large staff of highly skilled security personnel. Therefore, they should be accessible to most enterprise organizations. This configuration is applicable to most mobile users accessing work or school data on a device.
```

2022-04-19 04:13 UTC, JohanFreelancer9 requested changes
Apologies @msbemba, one more, please.

2022-04-19 12:11 UTC, yogkumgit commented
@msbemba

2022-04-20 14:38 UTC, lenewsad commented
#sign-off

2022-04-20 23:26 UTC, PRMerger12 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-21 03:55 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-04-21 15:12 UTC, merged