Update app-configuration-policies-overview.md
MicrosoftDocs/memdocs pull request #2681
Opened 2022-04-12 13:49 UTC by msbemba

Updated the steps to Type about:intunehelp in the address box. instead of clicking on about intune help as it does not show up any more(tested in 2 devices)

2022-04-12 13:49 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-04-13 04:49 UTC, JohanFreelancer9 commented on memdocs/intune/apps/app-configuration-policies-overview.md
> +2. Launch the **Microsoft Edge** and Type about:intunehelp in the address box.
```suggestion
2. Launch the **Microsoft Edge** and enter **about:intunehelp** in the address box.
```

2022-04-13 04:49 UTC, JohanFreelancer9 commented on memdocs/intune/apps/app-configuration-policies-overview.md
> +2. Launch **Microsoft Edge** and Type about:intunehelp in the address box.
```suggestion
2. Launch **Microsoft Edge** and enter **about:intunehelp** in the address box.
```

2022-04-13 04:50 UTC, JohanFreelancer9 requested changes
Copy review.

2022-04-13 07:03 UTC, PRMerger13 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-13 09:24 UTC, JohanFreelancer9 approved these changes

2022-04-16 04:14 UTC, yogkumgit commented
@Erikre Please merge this PR. Thanks

2022-05-02 20:30 UTC, Erikre approved these changes

2022-05-02 20:30 UTC, Erikre commented
#sign-off

2022-05-03 11:27 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-05-03 19:57 UTC, merged