Update app-sdk-ios.md
MicrosoftDocs/memdocs pull request #2682
Opened 2022-04-12 14:49 UTC by msbemba

Added Appstore Submission Note

2022-04-12 14:50 UTC, msbemba commented
@JohanFreelancer9 Please copy review.

2022-04-12 14:50 UTC, PRMerger3 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-13 04:39 UTC, JohanFreelancer9 approved these changes

2022-04-16 04:16 UTC, yogkumgit commented
@Erikre Please merge this PR. Thanks

2022-05-24 05:01 UTC, yogkumgit commented
@Erikre

2022-05-24 11:48 UTC, JohanFreelancer9 commented on memdocs/intune/developer/app-sdk-ios.md
> +   > If you use the framework, you must manually strip out the simulator architectures from the universal framework before you submit your app to the App Store. See [Submit your app to the App Store]
```suggestion
   > If you use Framework, you must manually strip out the simulator architectures from the universal framework before you submit your app to the App Store. See [Submit your app to the App Store](#submit-your-app-to-the-app-store) for more details.
```

2022-05-24 11:50 UTC, JohanFreelancer9 commented on memdocs/intune/developer/app-sdk-ios.md
> +Both the static library and framework builds of the Intune App SDK are universal binaries. This means they have code for all device and simulator architectures. Apple will reject apps submitted to th
```suggestion
Both the static library and Framework builds of the Intune App SDK are universal binaries. This means they have code for all device and simulator architectures. Apple will reject apps submitted to the App Store if they have simulator code. When compiling against the static library for device-only builds, the linker will automatically strip out the simulator code. Follow these steps to ensure all simulator code is removed before you upload your app to the App Store:
```

2022-05-24 11:52 UTC, JohanFreelancer9 requested changes
@msbemba, please commit these changes. Many thanks.

2022-05-24 12:26 UTC, PRMerger12 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-24 12:26 UTC, PRMerger14 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-24 14:36 UTC, JohanFreelancer9 approved these changes

2022-05-25 05:40 UTC, yogkumgit commented
@Erikre Please review and signoff this PR. Thanks

2022-06-23 03:19 UTC, yogkumgit commented
@Erikre Gentle reminder

2022-08-29 23:28 UTC, Erikre commented
#sign-off

2022-08-30 07:08 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-08-30 15:36 UTC, tiburd commented on memdocs/intune/developer/app-sdk-ios.md
> +   > If you use Framework, you must manually strip out the simulator architectures from the universal framework before you submit your app to the App Store. See [Submit your app to the App Store](#su
```suggestion
   > If you use Framework, you must manually strip out the simulator architectures from the universal framework before you submit your app to the App Store. For more information, see [Submit your app to the App Store](#submit-your-app-to-the-app-store).
```

2022-08-30 15:39 UTC, merged