Update remote-help.md - Fix formatting on note
MicrosoftDocs/memdocs pull request #2712
Opened 2022-04-25 14:13 UTC by colealbrecht

Fix formatting on !Note under install and update

2022-04-25 14:13 UTC, PRMerger13 commented
@colealbrecht : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-04-29 04:57 UTC, JohanFreelancer9 commented on memdocs/intune/remote-actions/remote-help.md
> +> - On April 12th, 2022, existing users of remote help will see a mandatory upgrade screen when they open the remote help app. They will not be able to proceed until they upgrade to the latest versio
```suggestion
> - On April 5, 2022, existing users of remote help will see a recommended upgrade screen when they open the remote help app. Users will be able to continue using remote help without upgrading. 
> - On April 12, 2022, existing users of remote help will see a mandatory upgrade screen when they open the remote help app. They will not be able to proceed until they upgrade to the latest version of remote help.
```

2022-04-29 04:58 UTC, JohanFreelancer9 requested changes
Copy review - @colealbrecht, kindly commit the additional suggested changes. Many thanks.

2022-04-29 13:37 UTC, PRMerger8 commented
@colealbrecht : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-03 23:00 UTC, Smritib17 approved these changes

2022-05-03 23:00 UTC, merged