Update azure-virtual-desktop-multi-session.md
MicrosoftDocs/memdocs pull request #2720
Opened 2022-04-27 06:05 UTC by msbemba

Added a note about AADDS

2022-04-27 06:05 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-04-27 06:05 UTC, PRMerger9 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change. @smbhardwaj

2022-04-27 06:05 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2677

2022-04-27 06:13 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/azure-virtual-desktop-multi-session.md
> +> [!Note]
```suggestion
> [!NOTE]
```

2022-04-27 06:13 UTC, JohanFreelancer9 requested changes
Copy review.

2022-04-27 06:14 UTC, PRMerger12 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change. @smbhardwaj

2022-04-27 06:17 UTC, JohanFreelancer9 approved these changes

2022-04-29 12:07 UTC, yogkumgit commented
@SMBhardwaj Please review and signoff this PR. Thanks

2022-05-03 22:54 UTC, PRMerger8 commented
@Smritib17 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @smbhardwaj

2022-05-03 22:54 UTC, Smritib17 approved these changes

2022-05-03 22:54 UTC, merged