Update apps-win32-add.md
MicrosoftDocs/memdocs pull request #2797
Opened 2022-05-19 16:52 UTC by msbemba

Added more information about the path that it cannot contain " or ,

2022-05-19 16:52 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-05-19 16:52 UTC, PRMerger16 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-19 16:52 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2751

2022-05-20 05:07 UTC, JohanFreelancer9 commented on memdocs/intune/apps/apps-win32-add.md
> +        - **Path**: Enter the full path of the folder that contains the file or folder to detect. This should not include special characters like , or " .
```suggestion
        - **Path**: Enter the full path of the folder that contains the file or folder to detect. This should not include special characters such as **,** or **"**.
```

2022-05-20 05:07 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-20 06:37 UTC, PRMerger12 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-20 12:32 UTC, JohanFreelancer9 approved these changes

2022-05-23 20:24 UTC, Erikre approved these changes

2022-05-23 20:24 UTC, Erikre commented
#sign-off

2022-05-24 04:52 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-05-24 14:33 UTC, merged