Update windows-bulk-enroll.md
MicrosoftDocs/memdocs pull request #2813
Opened 2022-05-25 13:44 UTC by cbrito01

Our public docs does not contain any information on how to revoke a provisioning package after it is created. This is explained in the blog post below:
https://techcommunity.microsoft.com/t5/intune-customer-success/bulk-join-a-windows-device-to-azure-ad-and-microsoft-endpoint/ba-p/2381400#:~:text=This%20is%20the%20placeholder%20account%20used%20for%20joining%20the%20devices%2C%20and%20an%20easy%20way%20of%20invalidating%20the%20provisioning%20package%20before%20it%20expires%20automatically%20would%20be%20to%20remove%20this%20account.

2022-05-26 05:25 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/windows-bulk-enroll.md
> +[!NOTE] Once a provisioning package is created, it can be revoked before its expiration by removing the associated package_{GUID} user account from Azure AD.
```suggestion
> [!NOTE]
> Once a provisioning package is created, it can be revoked before its expiration by removing the associated package_{GUID} user account from Azure AD.
```

2022-05-26 05:26 UTC, JohanFreelancer9 requested changes
Copy review - @cbrito01, kindly commit the suggested changes. Many thanks.

2022-05-26 05:30 UTC, PRMerger18 commented
@cbrito01 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-26 06:31 UTC, JohanFreelancer9 approved these changes

2022-06-06 05:25 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-06-06 17:08 UTC, merged