Update education-settings-configure-ios.md
MicrosoftDocs/memdocs pull request #2817
Opened 2022-05-26 13:42 UTC by msbemba

Fixed the intune URL part.

2022-05-26 13:42 UTC, PRMerger12 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-26 13:42 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-05-26 13:42 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2752

2022-05-26 15:23 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/education-settings-configure-ios.md
> +1. Sign in to [Intune]([https://go.microsoft.com/fwlink/?linkid=2090973](https://endpoint.microsoft.com)).
```suggestion
1. Sign in to [Intune](https://endpoint.microsoft.com)).
```

2022-05-26 15:24 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-26 15:32 UTC, PRMerger19 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-26 15:35 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/education-settings-configure-ios.md
> +1. Sign in to [Intune](https://endpoint.microsoft.com)).
```suggestion
1. Sign in to [Intune](https://endpoint.microsoft.com).
```

2022-05-26 15:38 UTC, PRMerger12 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-26 15:43 UTC, JohanFreelancer9 approved these changes

2022-05-27 07:15 UTC, yogkumgit commented
@lenewsad Please review and signoff this PR. Thanks

2022-06-03 12:33 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-06-03 15:34 UTC, merged