Update custom-notifications.md
MicrosoftDocs/memdocs pull request #2824
Opened 2022-05-30 14:19 UTC by msbemba

Added information that "Android Enterprise personally-owned with a work profile" supports custom notifications, but currently "Android Enterprise fully managed" does not.

2022-05-30 14:19 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-05-30 14:19 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2788

2022-05-30 14:19 UTC, PRMerger3 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-31 05:25 UTC, JohanFreelancer9 commented on memdocs/intune/remote-actions/custom-notifications.md
> +Use Microsoft Intune to send custom notifications to the users of managed iOS/iPadOS and Android devices. These messages appear as standard push notifications from the Company Portal app and from the
```suggestion
Use Microsoft Intune to send custom notifications to the users of managed iOS/iPadOS and Android devices. These messages appear as standard push notifications from the Company Portal app and from the Microsoft Intune app on a user's device, just as notifications from other applications on the device appear. Intune custom notifications aren't supported by macOS and Windows devices. Android Enterprise personally-owned with a work profile supports custom notifications, but currently, Android Enterprise fully managed does not. 
```

2022-05-31 05:25 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-31 06:38 UTC, PRMerger19 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-31 08:25 UTC, yogkumgit commented
@JohanFreelancer9

2022-05-31 08:26 UTC, yogkumgit commented
@Smritib17 Please review and signoff this PR. Thanks

2022-06-15 20:59 UTC, Smritib17 requested changes
Based on inputs from the PM I gather that AE fully managed devices do support custom notifications. However, the notification may not have showed up for the customer because of some reliability issue with custom notifications. 
This is documented here: [Send custom notifications to users with Microsoft Intune - Microsoft Intune | Microsoft Docs.](https://docs.microsoft.com/en-us/mem/intune/remote-actions/custom-notifications)
- _Intune, the Company Portal app, and the Microsoft Intune app, can't guarantee delivery of a custom notification. Custom notifications might show up after several hours of delay, if at all, so they shouldn't be used for urgent messages._

2022-06-16 07:08 UTC, msbemba commented
@Smritib17  Thank you for the clarification.

2022-06-16 07:08 UTC, closed without merging