Update azure-virtual-desktop-multi-session.md
MicrosoftDocs/memdocs pull request #2856
Opened 2022-06-07 12:44 UTC by SamzerOnGit

Comment on Co-management, like here https://docs.microsoft.com/en-us/mem/intune/protect/certificates-profile-scep#assign-the-certificate-profile

2022-06-07 12:45 UTC, PRMerger10 commented
@SamzerOnGit : Thanks for your contribution! The author(s) have been notified to review your proposed change. @smbhardwaj

2022-06-08 07:15 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/azure-virtual-desktop-multi-session.md
> +> [!NOTE] If you use co-management for Intune and Configuration Manager, in Configuration Manager [set the workload slider](/configmgr/comanage/how-to-switch-workloads) for Resource Access Policies t
```suggestion
> [!NOTE]
> If you use comanagement for Intune and Configuration Manager, in Configuration Manager, [set the workload slider](/configmgr/comanage/how-to-switch-workloads) for Resource Access Policies to **Intune** or **Pilot Intune**. This setting allows Windows 10 and Windows 11 clients to start the process of requesting the certificate.
```

2022-06-08 07:17 UTC, JohanFreelancer9 requested changes
Copy review - @SamzerOnGit, kindly commit the suggested changes. Many thanks.

2022-06-21 19:10 UTC, Smritib17 commented
#sign-off

2022-06-21 19:15 UTC, merged