Update app-wrapper-prepare-ios.md
MicrosoftDocs/memdocs pull request #2878
Opened 2022-06-16 19:13 UTC by fabianescacr

Adding a clarification for wrapping parameters -aa -ac and -ar which are required when MFA is used. This is one of the most generator of cases for the Intune Team in CSS as customer wrapping their apps and using MFA are not adding them

2022-06-16 19:13 UTC, PRMerger20 commented
@fabianescacr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-06-17 02:15 UTC, JohanFreelancer9 commented on memdocs/intune/developer/app-wrapper-prepare-ios.md
> +> If you are using MFA authentication then -aa -ac and -ar parameters are not optional. You need to specify them in order to allow the MFA redirection to work during the sign in process
```suggestion
> If you are using MFA authentication the -aa, -ac, and -ar parameters are not optional. You need to specify them in order to allow the MFA redirection to work during the sign-in process
```

2022-06-17 02:16 UTC, JohanFreelancer9 commented on memdocs/intune/developer/app-wrapper-prepare-ios.md
> +> **Example:** The following example command runs the App Wrapping Tool incorporating the required commands when MFA is used in the authentication process.
```suggestion
> **Example:** The following example command runs the App Wrapping Tool, incorporating the required commands when MFA is used in the authentication process.
```

2022-06-17 02:18 UTC, JohanFreelancer9 requested changes
Copy review - @fabianescacr, kindly commit the suggested changes. Many thanks.

2022-06-17 04:00 UTC, PRMerger20 commented
@fabianescacr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-06-17 06:43 UTC, JohanFreelancer9 approved these changes

2022-06-27 19:20 UTC, Erikre approved these changes

2022-06-27 19:21 UTC, Erikre commented
#sign-off

2022-06-28 18:22 UTC, merged