Update device-enrollment-shared-ipad.md
MicrosoftDocs/memdocs pull request #2884
Opened 2022-06-20 08:23 UTC by msbemba

In the known limitations section added info that the  available apps are not supported

2022-06-20 08:24 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2842

2022-06-20 08:24 UTC, PRMerger12 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-06-20 08:24 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-06-20 09:47 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/device-enrollment-shared-ipad.md
> +- **Company Portal and available apps are not supported:** Intune Company Portal app, the Intune Company Portal website are not supported on Shared iPads. Apps must be assigned as “required” to devic
```suggestion
- **Company Portal and available apps are not supported:** Intune Company Portal app and the Intune Company Portal website are not supported on Shared iPad. Apps must be assigned as “required” to device groups containing the Shared iPad to install. Available apps are not supported on Shared iPad.
```

2022-06-20 09:48 UTC, JohanFreelancer9 requested changes
Copy review.

2022-06-20 09:50 UTC, PRMerger20 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-06-20 14:28 UTC, JohanFreelancer9 approved these changes

2022-06-20 20:12 UTC, lenewsad approved these changes

2022-06-20 20:12 UTC, lenewsad commented
#sign-off

2022-06-22 03:51 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-06-22 15:44 UTC, merged