Add Crowdstrike Falcon instructions
MicrosoftDocs/memdocs pull request #2909
Opened 2022-07-01 01:02 UTC by elevenfive

2022-07-01 01:04 UTC, PRMerger4 commented
@elevenfive : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-01 08:12 UTC, JohanFreelancer9 commented on memdocs/intune/protect/mtd-apps-ios-app-configuration-policy-add-assign.md
> +  - See [Deploying Falcon for Mobile to Android devices](https://falcon.crowdstrike.com/documentation/185/Deploying-Falcon-for-Mobile-to-Android-devices)
```suggestion
  - See [Using Microsoft Intune app configuration policies for Android](../apps/app-configuration-policies-use-android.md).
  - See [Deploying Falcon for Mobile to Android devices](https://falcon.crowdstrike.com/documentation/185/Deploying-Falcon-for-Mobile-to-Android-devices).
```

2022-07-01 08:13 UTC, JohanFreelancer9 commented on memdocs/intune/protect/mtd-apps-ios-app-configuration-policy-add-assign.md
> +  - See [Deploying Falcon for Mobile to iOS devices](https://falcon.crowdstrike.com/documentation/186/Deploying-Falcon-for-Mobile-to-iOS-devices)
```suggestion
  - See [using Microsoft Intune app configuration policies for iOS](../apps/app-configuration-policies-use-ios.md).
  - See [Deploying Falcon for Mobile to iOS devices](https://falcon.crowdstrike.com/documentation/186/Deploying-Falcon-for-Mobile-to-iOS-devices).
```

2022-07-01 08:15 UTC, JohanFreelancer9 requested changes
Copy review - @elevenfive, kindly commit the minor suggested changes. Many thanks.

2022-07-01 12:20 UTC, lornova commented on memdocs/intune/protect/mtd-apps-ios-app-configuration-policy-add-assign.md
> +  - See the instructions for [adding iOS store apps to Microsoft Intune](../apps/store-apps-ios.md). Use this [Check Point Harmony Mobile Protect app store URL](https://apps.apple.com/us/app/crowdstr
```suggestion
  - See the instructions for [adding iOS store apps to Microsoft Intune](../apps/store-apps-ios.md). Use this [Crowdstrike Falcon app store URL](https://apps.apple.com/us/app/crowdstrike-falcon/id1458815656) for the **Appstore URL**.  
```

2022-07-01 13:51 UTC, elevenfive commented on memdocs/intune/protect/mtd-apps-ios-app-configuration-policy-add-assign.md
> +  - See [Deploying Falcon for Mobile to Android devices](https://falcon.crowdstrike.com/documentation/185/Deploying-Falcon-for-Mobile-to-Android-devices)
Updated, thanks!

2022-07-01 13:51 UTC, elevenfive commented on memdocs/intune/protect/mtd-apps-ios-app-configuration-policy-add-assign.md
> +  - See [Deploying Falcon for Mobile to iOS devices](https://falcon.crowdstrike.com/documentation/186/Deploying-Falcon-for-Mobile-to-iOS-devices)
Updated, thanks!

2022-07-01 13:52 UTC, elevenfive commented on memdocs/intune/protect/mtd-apps-ios-app-configuration-policy-add-assign.md
> +  - See the instructions for [adding iOS store apps to Microsoft Intune](../apps/store-apps-ios.md). Use this [Check Point Harmony Mobile Protect app store URL](https://apps.apple.com/us/app/crowdstr
Thank you, updated!

2022-07-01 14:16 UTC, JohanFreelancer9 approved these changes

2022-07-05 15:08 UTC, Brenduns commented
Pending reveiw of supportability from PM/Dev.

2022-07-05 15:22 UTC, closed without merging