Update enrollment-restrictions-set.md
MicrosoftDocs/memdocs pull request #2915
Opened 2022-07-05 08:34 UTC by nahira-ms

Add iOS is supporeted IMEI.

Add blocking personal device on macOS

2022-07-05 08:34 UTC, PRMerger9 commented
@nahira-ms : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-05 10:45 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/enrollment-restrictions-set.md
>  - Enrolled by using Automated Device Enrollment (formerly Device Enrollment Program)
```suggestion
- Enrolled by using Automated Device Enrollment (formerly Device Enrollment Program).
```
```suggestion
- Enrolled by using Automated Device Enrollment (formerly Device Enrollment Program)
```

2022-07-05 10:46 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/enrollment-restrictions-set.md
> +
```suggestion
- Enrolled by using Automated Device Enrollment (formerly Device Enrollment Program).
```

2022-07-05 10:47 UTC, JohanFreelancer9 requested changes
Copy review - @nahira-ms, kindly commit the minor suggested changes. Many thanks.

2022-07-08 15:12 UTC, PRMerger5 commented
@lenewsad : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-08 15:13 UTC, PRMerger10 commented
@lenewsad : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-08 15:13 UTC, lenewsad commented
#sign-off

2022-07-09 06:21 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-07-18 15:35 UTC, lenewsad commented
#sign-off

2022-07-18 16:16 UTC, merged