Update email-settings-android-enterprise.md
MicrosoftDocs/memdocs pull request #2942
Opened 2022-07-15 13:26 UTC by msbemba

Added a pre req as Chrome app needs to be  installed in the work profile to enable modern auth for Gmail Per issue#https://github.com/MicrosoftDocs/memdocs/issues/2891 and support case

2022-07-15 13:26 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-07-15 13:26 UTC, PRMerger17 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-15 13:26 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2891

2022-07-15 16:56 UTC, JohanFreelancer9 commented on memdocs/intune/configuration/email-settings-android-enterprise.md
> +- Install Chrome App in the work profile to enable modern auth for Gmail.
```suggestion
- Install the Chrome app in the work profile to enable modern auth for Gmail.
```
```suggestion
- Install Chrome App in the work profile to enable modern auth for Gmail.
```

2022-07-15 16:57 UTC, JohanFreelancer9 commented on memdocs/intune/configuration/email-settings-android-enterprise.md
> +- Install Chrome App in the work profile to enable modern auth for Gmail.
```suggestion
- Install the Chrome app in the work profile to enable modern auth for Gmail.
```
```suggestion
- Install Chrome App in the work profile to enable modern auth for Gmail.
```

2022-07-15 16:58 UTC, JohanFreelancer9 requested changes
Copy review.

2022-07-15 17:12 UTC, PRMerger5 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-16 07:31 UTC, JohanFreelancer9 approved these changes

2022-07-18 05:24 UTC, yogkumgit commented
@MandiOhlinger Please review and signoff this PR. Thanks

2022-07-18 18:26 UTC, MandiOhlinger commented
Holding off on this PR. Requested more information in https://github.com/MicrosoftDocs/memdocs/issues/2891.

2022-07-21 15:53 UTC, PRMerger20 commented
@MandiOhlinger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-21 16:03 UTC, PRMerger4 commented
@MandiOhlinger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-21 16:05 UTC, MandiOhlinger approved these changes

2022-07-21 16:11 UTC, MandiOhlinger commented
@msbemba Thank you for making these changes. I updated the text. #sign-off

2022-07-21 16:11 UTC, merged