Update endpoint-security-edr-policy.md
MicrosoftDocs/memdocs pull request #2947
Opened 2022-07-16 23:26 UTC by msbemba

Updated Step 6

2022-07-16 23:26 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-07-16 23:26 UTC, PRMerger3 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-18 06:01 UTC, yogkumgit commented
@Brenduns Please review and merge this Pr. Thanks

2022-07-18 06:03 UTC, JohanFreelancer9 commented on memdocs/intune/protect/endpoint-security-edr-policy.md
> +6. On the **Configuration settings** page, Choose **Auto from Connector**  for **Microsoft Defender for Endpoint Clinet configuration package type**. Configure the **Sample Sharing** and **Telemetry
```suggestion
6. On the **Configuration settings** page, Choose **Auto from Connector** for **Microsoft Defender for Endpoint Client configuration package type**. Configure the **Sample Sharing** and **Telemetry Reporting Frequency** settings you want to manage with this profile. 
```

2022-07-18 06:04 UTC, JohanFreelancer9 requested changes
Copy review.

2022-07-18 06:04 UTC, yogkumgit commented
@msbemba

2022-07-19 05:51 UTC, yogkumgit commented
@msbemba gentle reminder

2022-07-19 17:31 UTC, merged