Update enrollment-restrictions-set.md
MicrosoftDocs/memdocs pull request #2955
Opened 2022-07-20 22:42 UTC by danivv96

2022-07-20 22:42 UTC, PRMerger4 commented
@danivv96 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-21 08:03 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/enrollment-restrictions-set.md
> +          > Windows does not provide revision(.rev) number to Intune during enrollment. So, the format to use in Enrollent Restriction Policy is "major.minor.build.0".
```suggestion
          > Windows does not provide a revision (.rev) number to Intune during enrollment. So, the format to use in Enrollment Restriction Policy is `major.minor.build.0`. 
```

2022-07-21 08:04 UTC, JohanFreelancer9 requested changes
Copy review - @danivv96, kindly commit the suggested changes. Many thanks.

2022-07-22 21:43 UTC, PRMerger5 commented
@danivv96 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-23 08:55 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/enrollment-restrictions-set.md
> +          > Windows does not provide a revision (.rev) number to Intune during enrollment. Therefore, the format to use in Enrollment Restriction Policy is `major.minor.build.0`.
```suggestion
          > Windows does not provide a revision (.rev) number to Intune during enrollment. Therefore, the format to use in Enrollment Restriction Policy is `major.minor.build.0`. 
```

2022-07-23 08:57 UTC, JohanFreelancer9 approved these changes

2022-08-15 18:40 UTC, lenewsad commented
Hi @danivv96, thank you for your contributions. I submitted one of the changes (removing "only") in a new PR. I am verifying the other change (new note) with the product team.

2023-02-07 11:02 UTC, yogkumgit commented
@lenewsad Kindly update Thanks

2023-02-08 02:05 UTC, lenewsad commented
Hi @yogkumgit, Pinging some additional SMEs to see if we can close this out.

2023-04-13 12:44 UTC, yogkumgit commented
@lenewsad Any update? Thanks

2023-04-25 20:52 UTC, lenewsad commented
Hi @danivv96, I confirmed with the product team that the format should be major.minor.build.0 as proposed. Thid PR is outdated so I made the change in a new PR. It should be live by end of day 4/25, PST. Thanks again for your contribution! 

CC: @yogkumgit

2023-04-25 21:24 UTC, closed without merging