Update backup-restore-ios.md
MicrosoftDocs/memdocs pull request #2960
Opened 2022-07-21 14:46 UTC by msbemba

Added a note about backing up the authenticator app before reset.

2022-07-21 14:47 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2870

2022-07-21 14:47 UTC, PRMerger12 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-21 14:47 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-07-22 04:52 UTC, yogkumgit commented
@lenewsad Please review and Signoff this PR. Thanks

2022-07-22 10:32 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/backup-restore-ios.md
> +> If you are using Microsoft authenticator App, it is important to back up the credentials and accounts before factory reset. For more information, visit [Back up and recover account credentials in t
```suggestion
> If you are using Microsoft Authenticator app, it is important to back up the credentials and accounts before factory reset. For more information, visit [Back up and recover account credentials in the Authenticator app](https://support.microsoft.com/account-billing/back-up-and-recover-account-credentials-in-the-authenticator-app-bb939936-7a8d-4e88-bc43-49bc1a700a40#:~:text=The%20Microsoft%20Entra%20Authenticator%20app,or%20having%20to%20recreate%20accounts.)
```

2022-07-22 10:33 UTC, JohanFreelancer9 requested changes
Copy review.

2022-07-22 12:34 UTC, PRMerger20 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-23 06:10 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/backup-restore-ios.md
> +> If you are using Microsoft Authenticator app, it is important to back up the credentials and accounts before factory reset. For more information, visit [Back up and recover account credentials in t
```suggestion
> If you are using Microsoft Authenticator app, it is important to back up the credentials and accounts before factory reset. For more information, visit [Back up and recover account credentials in the Authenticator app](https://support.microsoft.com/account-billing/back-up-and-recover-account-credentials-in-the-authenticator-app-bb939936-7a8d-4e88-bc43-49bc1a700a40#:~:text=The%20Microsoft%20Entra%20Authenticator%20app,or%20having%20to%20recreate%20accounts.).
```

2022-07-23 06:10 UTC, JohanFreelancer9 requested changes
Apologies @msbemba, one more, please.

2022-07-23 11:46 UTC, PRMerger4 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-25 04:12 UTC, yogkumgit commented
@JohanFreelancer9

2022-07-25 04:13 UTC, yogkumgit commented
@lenewsad Please review and Signoff this PR. Thanks

2022-07-25 16:17 UTC, lenewsad commented
#sign-off

2022-07-26 04:09 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-07-26 15:04 UTC, merged