Update remote-help.md
MicrosoftDocs/memdocs pull request #2961
Opened 2022-07-21 14:51 UTC by msbemba

Added a pre requisite per issue#https://github.com/MicrosoftDocs/memdocs/issues/2939

2022-07-21 14:52 UTC, PRMerger13 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-21 14:52 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-07-22 06:35 UTC, JohanFreelancer9 commented on memdocs/intune/remote-actions/remote-help.md
> +-  Remote help will be available for M365 A1/A3/A5 Education customers later this calendar year. Education customers with M365 A1/A3/A5 which include Intune subscription will have Remote Help with th
```suggestion
-  Remote help will be available for Microsoft 365 A1/A3/A5 Education customers later this calendar year. Education customers with Microsoft 365 A1/A3/A5 which include Intune subscription will have remote help with their license and they won’t require the **Remote Help Add-on**.
```

2022-07-22 06:39 UTC, JohanFreelancer9 requested changes
Dear @msbemba. I have done a copy review, but I am not too sure about including this prerequisite. The latest guidance is that we don't make announcements in docs content and avoid talking about future events. Thanks.

2022-07-22 07:02 UTC, dougeby commented
> Dear @msbemba. I have done a copy review, but I am not too sure about including this prerequisite. The latest guidance is that we don't make announcements in docs content and avoid talking about future events. Thanks.

I agree. We don't ever provide information about what will be available with particular licenses at a particular date even if it's something that was already announced. I'm also curious how the information was vetted for accuracy.

2022-07-22 13:03 UTC, msbemba commented
@dougeby and @JohanFreelancer9  Thank you for that information. I'll close this PR. I viewed a Roadmap that said Rolled out (but in preview for Edu) so that was the confusion.  I'll ensure that I add information only after the product is live and do not commit when it is in roadmap.

![image](https://user-images.githubusercontent.com/45987684/180444713-06fe394d-327d-40ea-a846-8fb4bb0b577c.png)

Thanks
Sri

2022-07-22 13:04 UTC, closed without merging