updated with license requirement
MicrosoftDocs/memdocs pull request #2978
Opened 2022-07-28 07:53 UTC by DevOpsStyle

Azure Virtual Desktop Multi-Session Session Host can be enrolled in intune. As Multi-Session Device don't have a primary user at least is needed to have a valid device license assigned to the device in order to complete the enrollment following the compliance policy.

Thank you

2022-07-28 07:53 UTC, PRMerger7 commented
@DevOpsStyle : Thanks for your contribution! The author(s) have been notified to review your proposed change. @smbhardwaj

2022-07-29 09:17 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/azure-virtual-desktop-multi-session.md
> +- A valid device only license [Microsoft Intune licensing](/memdocs/intune/fundamentals/licenses.md)
```suggestion
- A valid device-only license. For more information, see [Microsoft Intune licensing](/memdocs/intune/fundamentals/licenses.md).
```

2022-07-29 09:17 UTC, JohanFreelancer9 requested changes
Copy review - @DevOpsStyle, kindly commit the suggested change. Many thanks.

2022-07-30 08:16 UTC, PRMerger3 commented
@DevOpsStyle : Thanks for your contribution! The author(s) have been notified to review your proposed change. @smbhardwaj

2022-07-30 08:17 UTC, DevOpsStyle commented
@JohanFreelancer9 committed with your suggestions. Thank you

2022-07-30 08:54 UTC, JohanFreelancer9 approved these changes

2022-08-03 22:10 UTC, Smritib17 commented
Note that the same issue was raised in the PR: https://github.com/MicrosoftDocs/memdocs/pull/2974 and it has been addressed after getting feedback from the PM. You can close this PR as it is a duplicate.

2022-08-05 07:33 UTC, closed without merging