Update unenroll-your-device-from-intune-windows.md
MicrosoftDocs/memdocs pull request #2991
Opened 2022-07-31 23:55 UTC by msbemba

Removed the remove option (company portal ) as it is no longer available

It has only Rename, Reset and Reset PIN options

Issue#https://github.com/MicrosoftDocs/memdocs/issues/2977

2022-07-31 23:55 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-07-31 23:55 UTC, PRMerger19 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-08-01 05:21 UTC, JohanFreelancer9 commented on memdocs/intune/user-help/unenroll-your-device-from-intune-windows.md
>  This section describes how to remove a Windows 10/11 device from Intune. If one set of instructions doesn't work for you, try the next set.
```suggestion
This section describes how to remove a Windows 10/11 device from Intune.   
```

2022-08-01 05:21 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-01 13:31 UTC, PRMerger7 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-08-01 14:08 UTC, JohanFreelancer9 approved these changes

2022-08-01 14:34 UTC, yogkumgit commented
@lenewsad Please review and signoff this Pr. Thanks

2022-08-02 16:49 UTC, lenewsad commented
#sign-off

2022-08-03 11:28 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-08-04 00:35 UTC, merged