Update store-apps-windows.md
MicrosoftDocs/memdocs pull request #2996
Opened 2022-08-01 00:30 UTC by msbemba

Made changes to the navigation as the Microsoft store interface has changed

2022-08-01 00:30 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2952

2022-08-01 00:30 UTC, PRMerger8 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-08-01 00:30 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-01 05:56 UTC, JohanFreelancer9 commented on memdocs/intune/apps/store-apps-windows.md
> +5. To configure the **App information** for Microsoft store apps, navigate to the [Microsoft store](https://www.microsoft.com/store/apps), Click on **Open Store Apps** and search for the app you want
```suggestion
5. To configure the **App information** for Microsoft store apps, navigate to the [Microsoft store](https://www.microsoft.com/store/apps), select **Open Store Apps**, and search for the app you want to deploy. Display the app page and make a note of the app details. 
```

2022-08-01 05:57 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-01 13:27 UTC, PRMerger4 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-08-01 13:39 UTC, yogkumgit commented
@msbemba

2022-08-01 13:43 UTC, JohanFreelancer9 approved these changes

2022-08-01 14:42 UTC, yogkumgit commented
@Erikre Please review and Sign Off this PR. Thanks

2022-08-12 12:58 UTC, yogkumgit commented
@Erikre Gentle reminder

2022-08-29 23:15 UTC, Erikre approved these changes

2022-08-29 23:15 UTC, Erikre commented
#sign-off

2022-08-30 07:02 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-08-30 15:25 UTC, merged