Update description of device report view
MicrosoftDocs/memdocs pull request #2997
Opened 2022-08-01 05:02 UTC by ravisha22

Added description to provide more information on the data being displayed at the device report

2022-08-01 05:02 UTC, PRMerger16 commented
@ravisha22 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-08-01 06:37 UTC, JohanFreelancer9 commented on windows-365/enterprise/report-remoting-connection.md
> +>There might days when users login and the graph does display those days. This is due to the way the graph calculations exclude certain edge cases that can provide wrong data.
```suggestion
When you select a particular device in one of the reports, you'll see specific information for that device. The information displayed is for the last 14 days of usage with values aggregated for each day individually. If the user has not signed in to Cloud PC for a particular day, that day will not show in the graph.

> [!NOTE]
> There might be days when users have signed in and the graph does not display those days. This is due to the way the graph calculations exclude certain Edge cases that can provide incorrect data.
```

2022-08-01 06:37 UTC, JohanFreelancer9 requested changes
Copy review - @ravisha22, kindly commit the suggested changes. Many thanks.

2022-08-01 07:34 UTC, PRMerger-2 commented
@ravisha22 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-08-01 13:00 UTC, JohanFreelancer9 approved these changes

2022-08-24 16:24 UTC, ErikjeMS commented
#sign-off

2022-08-24 16:28 UTC, ErikjeMS commented
This section was already updated in a PR on the private repo. So, closing this PR.

2022-08-24 16:28 UTC, closed without merging