Update encrypt-devices.md
MicrosoftDocs/memdocs pull request #3015
Opened 2022-08-05 11:00 UTC by msbemba

Cleared the ambiguity as Compatible TPM startup PIN or Key  must not be set to Require startup PIN or key

2022-08-05 11:00 UTC, msbemba commented
IssuE#https://github.com/MicrosoftDocs/memdocs/issues/3003

2022-08-05 11:00 UTC, PRMerger17 commented
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-08-05 11:00 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-05 13:49 UTC, JohanFreelancer9 commented on memdocs/intune/protect/encrypt-devices.md
> +A device **must not be set to require**  startup PIN or startup key.
```suggestion
A device **must not be set to require** a startup PIN or startup key.
```

2022-08-05 13:49 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-05 15:34 UTC, yogkumgit commented
@msbemba

2022-08-12 12:58 UTC, yogkumgit commented
@msbemba Gentle reminder

2022-08-13 07:49 UTC, JohanFreelancer9 approved these changes

2022-08-15 05:49 UTC, yogkumgit commented
@Brenduns Please review and signoff this PR. Thanks

2022-08-15 14:34 UTC, Brenduns commented
#sign-off

2022-08-16 07:39 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-08-16 17:34 UTC, merged