Update use-microsoft-tunnel-ios.md
MicrosoftDocs/memdocs pull request #3041
Opened 2022-08-12 14:43 UTC by msbemba

App no longer available in the app store as the support ended. So removed the statement that talks about installing the same from the app store.

IssuE#https://github.com/MicrosoftDocs/memdocs/issues/3012

2022-08-12 14:43 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-12 17:07 UTC, JohanFreelancer9 commented on memdocs/intune/user-help/use-microsoft-tunnel-ios.md
```suggestion
```

2022-08-12 17:07 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-12 18:44 UTC, lenewsad commented
#sign-off

2022-08-13 06:23 UTC, JohanFreelancer9 approved these changes

2022-08-15 05:28 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-08-15 17:21 UTC, merged