Update mdm-supported-devices.md
MicrosoftDocs/memdocs pull request #3071
Opened 2022-08-24 06:47 UTC by Reethan-Raj

2022-08-24 08:51 UTC, JohanFreelancer9 commented on memdocs/intune/includes/mdm-supported-devices.md
> +> Intune requires iOS 13.x or higher for device enrollment scenarios and app configuration delivered through Managed devices app configuration policies.
```suggestion
> Intune requires iOS 13.x or later for device enrollment scenarios and app configuration delivered through Managed devices app configuration policies.
```

2022-08-24 08:54 UTC, JohanFreelancer9 requested changes
Copy review - @Reethan-Raj, kindly commit the suggested changes. Many thanks.

2022-08-24 16:20 UTC, ErikjeMS commented
#sign-off

2022-08-25 03:36 UTC, JohanFreelancer9 requested changes
@Reethan-Raj - thank you for committing my changes, but you seem to have missed one. Could you please commit that as well? Many thanks.

2022-08-25 12:43 UTC, JohanFreelancer9 approved these changes

2022-08-26 19:12 UTC, merged