Update Show/Hide Device to Device Migration
MicrosoftDocs/memdocs pull request #3074
Opened 2022-08-24 20:36 UTC by Urbs3w

**Show/Hide Device to Device Migration** has no effect on destination devices with iOS/iPadOS 13.0 and later that are already enrolled with Apple. The option will not be shown. If this information were published here, it may save untold hours of frustration trying to make the option show up 😃  

Sources
 - https://www.reddit.com/r/Intune/comments/dfj8vv/has_anyone_gotten_device_to_device_migration_to/
 - https://developer.apple.com/forums/thread/123433
 - https://social.technet.microsoft.com/Forums/en-US/9faf8e23-3bfe-4b0e-90d9-51bf2a3c40b0/device-to-device-migration?forum=microsoftintuneprod
 - Personal experience

Regards,
Urbs3w

2022-08-26 08:04 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/device-enrollment-program-enroll-ios.md
> +    | **Device to Device Migration** | On destination devices with iOS/iPadOS 13.0 and later that are already enrolled with Apple, this setting does not have an effect. On such devices, the Apps & Da
```suggestion
    | **Device to Device Migration** | On destination devices with iOS/iPadOS 13.0 and later that are already enrolled with Apple, this setting does not have an effect. On such devices, the Apps & Data screen does not display the option to do a device-to-device transfer. Furthermore, the Quick Start screen may indicate that Quick Start can do a device-to-device migration, however, if run, it will finish immediately without transferring any data.
```

2022-08-26 08:05 UTC, JohanFreelancer9 requested changes
Copy review - @Urbs3w, kindly commit the suggested changes. Many thanks.

2022-08-26 15:50 UTC, JohanFreelancer9 approved these changes

2022-08-26 16:09 UTC, lenewsad commented
Hi @Urbs3w, thanks for your contribution! I'm verifying it with the product team.

2022-09-02 18:22 UTC, lenewsad commented
Thank you @Urbs3w for the contribution and for the doc references.

2022-09-02 18:23 UTC, lenewsad commented
#sign-off

2022-09-06 17:16 UTC, merged