Update device-compliance-get-started.md
MicrosoftDocs/memdocs pull request #3075
Opened 2022-08-25 12:02 UTC by msbemba

Added a note per Microsoft submitter's information. Might have to check with PG on the accuracy.

Per issue#https://github.com/MicrosoftDocs/memdocs/issues/3044

2022-08-25 12:03 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-25 14:00 UTC, Brenduns commented
@sign-off

2022-08-26 09:50 UTC, JohanFreelancer9 commented on memdocs/intune/protect/device-compliance-get-started.md
> +> The Company Portal enters the enrollment remediation flow when the user logs into CP and the device has not successfully checked in with Intune in 30+ days (or the device is noncompliant due to a "
```suggestion
> The Company Portal app enters the enrollment remediation flow when the user signs into the Company Portal app and the device has not successfully checked in with Intune for 30 days or more (or the device is noncompliant due to a _Lost contact_ compliance reason). In this flow, we attempt to initiate a check-in one more time. If that still does not succeed, we issue a retire command to allow the user to re-enroll the device manually.
```

2022-08-26 09:54 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-26 10:51 UTC, JohanFreelancer9 approved these changes

2022-08-29 14:22 UTC, merged