Add HTA ADK1122H2 known issue
MicrosoftDocs/memdocs pull request #3094
Opened 2022-08-30 07:47 UTC by Ismawell

Add Known issues about HTA applications and ADK for Windows 11, version 22H2

2022-08-31 07:44 UTC, JohanFreelancer9 commented on memdocs/configmgr/mdt/known-issues.md
> +After you updated your MDT boot image to [ADK for Windows 11, version 22H2](/windows-hardware/get-started/adk-install), HTA applications stop working and a message box is displayed: Script Error - An
```suggestion
After you updated your MDT boot image to [ADK for Windows 11, version 22H2](/windows-hardware/get-started/adk-install), HTA applications stop working and a message box is displayed: Script Error - An error has occurred in the script on this page.
```

2022-08-31 07:46 UTC, JohanFreelancer9 commented on memdocs/configmgr/mdt/known-issues.md
> +HTA applications relies on MSHTML and starting Windows 11, version 22H2, the default legacy scripting engine was changed.
```suggestion
HTA applications rely on MSHTML and starting with Windows 11, version 22H2, the default legacy scripting engine was changed.
```

2022-08-31 07:46 UTC, JohanFreelancer9 commented on memdocs/configmgr/mdt/known-issues.md
> +To workaround the issue, you need to add the following registry value in WinPE:
```suggestion
To work around this issue you need to add the following registry value in WinPE: 
```

2022-08-31 07:49 UTC, JohanFreelancer9 commented on memdocs/configmgr/mdt/known-issues.md
> +To enable this change in MDT, we recommand you to backup the following file C:\Program Files\Microsoft Deployment Toolkit\Templates\Unattend_PE_x64.xml and to modify it like this:
```suggestion
To enable this change in MDT, we recommend that you back up the following file: `C:\Program Files\Microsoft Deployment Toolkit\Templates\Unattend_PE_x64.xml` and to modify it as follows:
```

2022-08-31 07:53 UTC, JohanFreelancer9 requested changes
Copy review - @Ismawell, kindly commit the suggested changes. Many thanks.

2022-09-02 02:14 UTC, JohanFreelancer9 commented on memdocs/configmgr/mdt/known-issues.md
> +To enable this change in MDT, we recommend that you back up the following file: `C:\Program Files\Microsoft Deployment Toolkit\Templates\Unattend_PE_x64.xml` and to modify it as follows:
```suggestion
To enable this change in MDT, we recommend that you back up the following file: `C:\Program Files\Microsoft Deployment Toolkit\Templates\Unattend_PE_x64.xml` and modify it as follows:
```

2022-09-02 02:15 UTC, JohanFreelancer9 requested changes
@Ismawell, thank you for committing the suggested changes. Kindly also commit the minor additional suggested change. Many thanks.

2022-09-16 17:18 UTC, BalaDelli approved these changes
#sign-off

2022-09-19 04:39 UTC, JohanFreelancer9 approved these changes

2022-09-22 19:31 UTC, merged