Update lob-apps-macos.md
MicrosoftDocs/memdocs pull request #3112
Opened 2022-09-05 10:10 UTC by Base51

Include a note, with the same statement from out news, where "intunemac" was removed.
https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#plan-for-change-deploy-macos-lob-apps-by-uploading-pkg-type-installer-files
"In August 2022, we removed the ability to upload wrapped .intunemac files in the Microsoft Endpoint Manager admin center." 
**Maybe include also the link.**

2022-09-06 09:12 UTC, JohanFreelancer9 commented on memdocs/intune/apps/lob-apps-macos.md
> +> In August 2022, we removed the ability to upload wrapped .intunemac files in the Microsoft Endpoint Manager admin center.
```suggestion
>
> In August 2022, we removed the ability to upload wrapped .intunemac files in the Microsoft Endpoint Manager admin center. 
```

2022-09-06 09:17 UTC, JohanFreelancer9 requested changes
Copy review - @Base51, kindly commit the suggested change. Many thanks.

2022-09-20 19:52 UTC, Erikre approved these changes

2022-09-21 11:26 UTC, JohanFreelancer9 approved these changes

2022-10-28 13:11 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-10-28 15:11 UTC, merged