Manage teams apps on Office mobile
MicrosoftDocs/memdocs pull request #3141
Opened 2022-09-15 05:07 UTC by harshatms

Allow, block teams apps on office mobile.

2022-09-16 03:21 UTC, JohanFreelancer9 commented on memdocs/intune/apps/manage-microsoft-office.md
> +Teams personal tab apps are already in Preview for Office.com and Outlook desktop in Target Release, and IT admins can manage access to Teams apps by creating [custom permission policies](https://doc
```suggestion
Teams personal tab apps are already in preview for Office.com and Outlook desktop in Target Release, and IT admins can manage access to Teams apps by creating [custom permission policies](/MicrosoftTeams/teams-app-permission-policies#create-a-custom-app-permission-policy) and [assigning these policies to users](/MicrosoftTeams/policy-assignment-overview) using Teams admin center. You can now also run Teams personal tab apps in Office mobile on Android, in preview. Teams personal tab apps built using [Microsoft Teams JavaScript client SDK v2](/microsoftteams/platform/tabs/how-to/using-teams-client-sdk?tabs=javascript%2Cmanifest-teams-toolkit) (version 2.0.0) and [Teams App manifest](/microsoftteams/platform/resources/schema/manifest-schema) (version 1.13) will appear in Office mobile Android app under the “Apps” menu.
```

2022-09-16 03:24 UTC, JohanFreelancer9 commented on memdocs/intune/apps/manage-microsoft-office.md
> +To manage the above, you can use the following key:
```suggestion
- Only allow specific users in your organization to try enhanced Teams apps on Office mobile, or
- Block all users in your organization from using enhanced Teams apps on Office mobile.

To manage these,  you can use the following key:
```

2022-09-16 03:26 UTC, JohanFreelancer9 commented on memdocs/intune/apps/manage-microsoft-office.md
> +Above can also be used both by managed devices and managed apps.
```suggestion
This key can also be used both by managed devices and managed apps.
```

2022-09-16 03:31 UTC, JohanFreelancer9 requested changes
Copy review - @harshatms, kindly commit the suggested changes. Many thanks.

2022-09-16 03:59 UTC, JohanFreelancer9 commented on memdocs/intune/apps/manage-microsoft-office.md
> +### Manage Teams apps running on Office mobile on Android (in Preview)
```suggestion
### Manage Teams apps running on Office mobile on Android (in preview)
```

2022-09-16 05:05 UTC, harshatms commented on memdocs/intune/apps/manage-microsoft-office.md
> +Above can also be used both by managed devices and managed apps.
Removed "also".

2022-09-16 05:08 UTC, harshatms commented
@JohanFreelancer9 I have resolved comments.

2022-09-16 05:39 UTC, JohanFreelancer9 approved these changes

2022-09-16 14:59 UTC, JohanFreelancer9 commented on memdocs/intune/apps/manage-microsoft-office.md
> +- Manage Teams apps running on Office app for Android (in Preview)
```suggestion
- Manage Teams apps running on Office app for Android (in preview)
```

2022-09-16 14:59 UTC, JohanFreelancer9 requested changes
Thank you for committing the suggested changes. Yes, the relative links will definitely work once these changes have been merged. And my apologies, could you please also commit the one that I've missed? Thanks again.

2022-09-16 15:37 UTC, harshatms commented
> Thank you for committing the suggested changes. Yes, the relative links will definitely work once these changes have been merged. And my apologies, could you please also commit the one that I've missed? Thanks again.

Thanks for clarification. I have committed suggestions.

2022-09-16 17:06 UTC, Erikre commented
#sign-off

2022-09-19 05:37 UTC, harshatms commented
@Erikre and @JohanFreelancer9 how can I merge this PR?

2022-09-19 08:56 UTC, JohanFreelancer9 approved these changes

2022-09-19 08:58 UTC, JohanFreelancer9 commented
@yogkumgit, can you please help to get this PR merged? Many thanks.

2022-09-20 03:57 UTC, harshatms commented
> @yogkumgit, can you please help to get this PR merged? Many thanks.

2022-09-20 05:12 UTC, harshatms commented
@yogkumgit kindly help in merging this.

2022-09-20 08:11 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-09-20 16:56 UTC, merged