Update licenses.md
MicrosoftDocs/memdocs pull request #3186
Opened 2022-09-29 11:35 UTC by msbemba

Updated navigation to get license information

2022-09-29 11:35 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/3154

2022-09-29 11:35 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-09-29 17:03 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/licenses.md
> +2. Select **Azure Active Directory**. Under **Manage** > **Select Licenses** > **All products** > **Select the License** and choose **Service Plan details** to view your license.
```suggestion
2. Select **Azure Active Directory**.
3. Select **Manage** > **Select Licenses** > **All products** > **Select the License** and choose **Service Plan details** to view your license.
```

2022-09-29 17:04 UTC, JohanFreelancer9 requested changes
Copy review.

2022-09-30 06:39 UTC, JohanFreelancer9 approved these changes

2022-09-30 10:29 UTC, yogkumgit commented
@Erikre Please review and Signoff this PR. Thanks

2022-12-22 20:11 UTC, Erikre commented
#sign-off

2022-12-22 20:13 UTC, traya1 commented
Learn Build status updates of commit _[b32463d](https://github.com/msbemba/memdocs/commits/b32463d07ca25e9ff31601676235fca5ab446900)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[memdocs/intune/fundamentals/licenses.md](https://github.com/msbemba/memdocs/blob/patch-154/memdocs/intune/fundamentals/licenses.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/aa268e4d-aaaf-30c8-4118-35d62ca794c9/202212222011267557-3186/BuildReport?accessString=836108869c06ac343318a55330ab83c243ddae04cc4864a77fdaec52e92a4782).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/aa268e4d-aaaf-30c8-4118-35d62ca794c9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-23 12:25 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-12-27 17:41 UTC, merged