Update remote-help.md
MicrosoftDocs/memdocs pull request #3191
Opened 2022-10-03 06:06 UTC by msbemba

updated a note stating that The message function of Remote Help only supports single byte characters as the current limit.

per issue#https://github.com/MicrosoftDocs/memdocs/issues/3179

2022-10-03 06:06 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-10-03 07:54 UTC, JohanFreelancer9 commented on memdocs/intune/remote-actions/remote-help.md
> +> The message function of Remote Help only supports single byte characters as the current limit.
```suggestion
> The message function of remote help only supports single-byte characters as the current limit.
```

2022-10-03 07:54 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-03 08:59 UTC, JohanFreelancer9 approved these changes

2022-10-03 12:27 UTC, yogkumgit commented
@Smritib17 Please review and signoff this PR. Thanks

2022-10-18 19:32 UTC, Smritib17 approved these changes

2022-10-18 19:32 UTC, Smritib17 commented
#sign-off

2022-10-18 19:33 UTC, merged