Update zoom-support.md
MicrosoftDocs/memdocs pull request #3208
Opened 2022-10-09 19:16 UTC by christiaanbrinkhoff

Updates regarding the Windows 365 app release.

2022-10-10 05:36 UTC, JohanFreelancer9 commented on windows-365/enterprise/zoom-support.md
> +- - **Windows Remote Desktop Client**: These instructions don't support connections through a web browser.
```suggestion
- **Windows Remote Desktop Client**: These instructions don't support connections through a web browser.
```

2022-10-10 05:40 UTC, JohanFreelancer9 requested changes
Copy review - @christiaanbrinkhoff, kindly commit the minor suggested change. Many thanks.

2022-10-24 18:53 UTC, ErikjeMS commented
#sign-off

2022-10-25 07:39 UTC, JohanFreelancer9 approved these changes

2023-02-14 19:07 UTC, merged