Update cisco-webex-support.md
MicrosoftDocs/memdocs pull request #3209
Opened 2022-10-09 19:17 UTC by christiaanbrinkhoff

2022-10-09 19:17 UTC, christiaanbrinkhoff commented
Windows 365 app release documentation changes.

2022-10-10 05:42 UTC, JohanFreelancer9 commented on windows-365/enterprise/cisco-webex-support.md
> +- - **Windows Remote Desktop Client**: These instructions don't support connections through a web browser.
```suggestion
- **Windows Remote Desktop Client**: These instructions don't support connections through a web browser.
```

2022-10-10 05:43 UTC, JohanFreelancer9 requested changes
Copy review - @christiaanbrinkhoff, kindly commit the minor suggested change. Many thanks.

2022-10-24 18:55 UTC, ErikjeMS commented
This seems to be a duplicate to PR 3208. Closing.

2022-10-24 18:55 UTC, closed without merging