Update add-device-images.md
MicrosoftDocs/memdocs pull request #3215
Opened 2022-10-11 06:35 UTC by kmsft

there is a 20-machine simultaneous limit for "managed images" https://learn.microsoft.com/en-us/azure/virtual-machines/windows/capture-image-resource which customers are not subject to because W365 uses Azure Compute Gallery

will reach out to W365 PM about this change

2022-10-12 07:58 UTC, JohanFreelancer9 commented on windows-365/enterprise/add-device-images.md
> +> - Custom device images are uploaded to the Windows 365 [Azure Compute Gallery](https://learn.microsoft.com/en-us/azure/virtual-machines/azure-compute-gallery) which supports over 20 concurrent depl
```suggestion
> - Custom device images are uploaded to the Windows 365 [Azure Compute Gallery](https://learn.microsoft.com/azure/virtual-machines/azure-compute-gallery) which supports over 20 concurrent deployments.
```

2022-10-12 07:59 UTC, JohanFreelancer9 requested changes
Copy review - @kmsft, kindly commit to the suggested change. Many thanks.

2022-10-13 10:13 UTC, JohanFreelancer9 approved these changes

2022-10-13 18:33 UTC, ErikjeMS commented
#sign-off

2022-10-13 23:45 UTC, elaineyou commented
Azure Computer Gallery is too deep a detail that customers don't need to know. Why don't we use the existing statement in "Device Images" doc as below:

If none of the default gallery images meet your requirements, you can upload up to 20 of your own custom device images.

2022-10-14 02:58 UTC, kmsft commented
I will propose: "If none of the default gallery images meet your requirements, you can upload your own custom device image."

The "20" is not a limit on the number of custom images that can be uploaded.  20 is the limit of simultaneous VMs that can be deployed with a single custom image.

The issue is a customer may be lead to believe W365 deployments will be limited to 20 simultaneous CPC deployment if they use a custom image and use the Managed Image method instead of Azure Compute Gallery.

A custom image uploaded to W365 is not subject to the 20 simultaneous deployments, because W365 uses Azure Compute Gallery behind the scenes.

From: Elaine You ***@***.***>
Sent: Friday, October 14, 2022 7:45 AM
To: MicrosoftDocs/memdocs ***@***.***>
Cc: Kingston Hui ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/memdocs] Update add-device-images.md (PR #3215)


Azure Computer Gallery is too deep a detail that customers don't need to know. Why don't we use the existing statement in "Device Images" doc as below:

If none of the default gallery images meet your requirements, you can upload up to 20 of your own custom device images.

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmemdocs%2Fpull%2F3215%23issuecomment-1278290425&data=05%7C01%7CKingston.Hui%40microsoft.com%7C06ef4b138cb44157507708daad74fde2%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C638013015256372900%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o69kEt4Q98juoTu0noj8laBoPa0T%2FY9GyHLouKGhpdY%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGJHEMCBFOAKZWQFVGW7CJLWDCNJDANCNFSM6AAAAAARB6LMTI&data=05%7C01%7CKingston.Hui%40microsoft.com%7C06ef4b138cb44157507708daad74fde2%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C638013015256372900%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cv2CE6QZTMa%2FACpYrhr4Vkq2Bkor%2BLubweaySzMNkqw%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2022-10-24 18:56 UTC, ErikjeMS commented
@kmsft Please recreate this PR in the private repo. Closing.

2022-10-24 18:56 UTC, closed without merging