Update device-images.md
MicrosoftDocs/memdocs pull request #3216
Opened 2022-10-11 06:46 UTC by kmsft

- clarified scope of M365 App image settings
- actions taken by W365

2022-10-12 08:09 UTC, JohanFreelancer9 commented on windows-365/enterprise/device-images.md
> +  - Settings listed under **Images with OS optimizations**
```suggestion
  - Settings listed under **Images with OS optimizations**.
```

2022-10-12 08:14 UTC, JohanFreelancer9 commented on windows-365/enterprise/device-images.md
> +    - an Azure AD Join connection, Windows 365 replicates the image to the provisioned region during provisioning.
```suggestion
3. If you have a Hybrid Azure AD Join connection, Windows 365 replicates the image across all Azure regions where you have an Azure network connection.
4. If you have an Azure AD Join connection, Windows 365 replicates the image to the provisioned region during provisioning.
```

2022-10-12 08:16 UTC, JohanFreelancer9 commented on windows-365/enterprise/device-images.md
> +    - an Azure AD Join connection, Windows 365 replicates the image to the provisioned region during provisioning.
I do not understand why the original formatting and text need to be changed. Could you please clarify?

2022-10-12 08:16 UTC, JohanFreelancer9 requested changes
Copy review - @kmsft, kindly commit the suggested changes. Many thanks.

2022-10-13 10:12 UTC, JohanFreelancer9 approved these changes

2022-10-13 18:35 UTC, ErikjeMS commented
#sign-off

2022-10-24 18:57 UTC, closed without merging