Update security.md
MicrosoftDocs/memdocs pull request #3219
Opened 2022-10-11 07:50 UTC by kmsft

updated with description from https://support.microsoft.com/en-us/topic/what-is-tpm-705f241d-025d-4470-80c5-4feeb24fa1ee the destination link also has a weird wording with "keys and measurements".  keys and setting would make more sense.

2022-10-12 08:39 UTC, JohanFreelancer9 commented on windows-365/enterprise/security.md
> +- **vTPM**: Short for virtual Trusted Platform Module, a vTPM provides Cloud PCs their own dedicate TPM instance that acts as a secure vault for cryptographic keys and to confirm that the operating s
```suggestion
- **vTPM**: Short for virtual Trusted Platform Module, a vTPM provides Cloud PCs their own dedicated TPM instance that acts as a secure vault for cryptographic keys to confirm that the operating system and firmware on your device are what they're supposed to be, and haven't been tampered with. For more information, see [vTPM](/azure/virtual-machines/trusted-launch#vtpm).
```

2022-10-12 08:40 UTC, JohanFreelancer9 requested changes
Copy review - @kmsft, kindly commit the suggested changes. Many thanks.

2022-10-13 09:54 UTC, JohanFreelancer9 approved these changes

2022-10-13 18:38 UTC, ErikjeMS commented
#sign-off

2022-10-24 18:59 UTC, closed without merging