Update assign-licenses.md
MicrosoftDocs/memdocs pull request #3228
Opened 2022-10-12 07:15 UTC by kmsft

added link to admin center for ease of navigation.  the URL is not listed anywhere in current docs making it slightly harder for new users

2022-10-12 11:57 UTC, JohanFreelancer9 commented on windows-365/enterprise/assign-licenses.md
> +- [Microsoft 365 admin center](https://admin.microsoft.com/) for individual users. For steps on how to use admin center to assign licenses, see [Assign licenses to users](/microsoft-365/admin/manage/
```suggestion
- [Microsoft 365 admin center](https://admin.microsoft.com/) for individual users. For steps on how to use the admin center to assign licenses, see [Assign licenses to users](/microsoft-365/admin/manage/assign-licenses-to-users).
```

2022-10-12 11:57 UTC, JohanFreelancer9 commented on windows-365/enterprise/assign-licenses.md
>  - To assign direct licenses to a list of individual users, see [Assign licenses for Windows 365](/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell) or see [Assi
```suggestion
- To assign direct licenses to a list of individual users, see [Assign licenses for Windows 365](/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell) or see [Assign license](/graph/api/user-assignlicense) to perform it through Graph.
```

2022-10-12 11:58 UTC, JohanFreelancer9 requested changes
Copy review - @kmsft, kindly commit the additional suggested changes. Many thanks.

2022-10-13 08:47 UTC, kmsft commented on windows-365/enterprise/assign-licenses.md
>  - To assign direct licenses to a list of individual users, see [Assign licenses for Windows 365](/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell) or see [Assi
hi @JohanFreelancer9 I would suggest skipping that part of the suggestion as those lines were replaced with a rewrite in https://github.com/MicrosoftDocs/memdocs/pull/3230/files/2bbfd196e31718f3e3beddc533d5ca1a10ad89e2

2022-10-13 09:31 UTC, JohanFreelancer9 approved these changes

2022-10-13 18:40 UTC, ErikjeMS commented
#sign-off

2022-10-24 19:00 UTC, ErikjeMS commented
@kmsft Please recreate this PR in the private repo. Closing.

2022-10-24 19:00 UTC, closed without merging