Update assign-licenses.md
MicrosoftDocs/memdocs pull request #3230
Opened 2022-10-12 07:41 UTC by kmsft

updated details on PowerShell vs Graph REST API

2022-10-12 12:05 UTC, JohanFreelancer9 commented on windows-365/enterprise/assign-licenses.md
> +- Graph REST API. See [Assign license](/graph/api/user-assignlicense)
```suggestion
- PowerShell. See [Assign licenses for Windows 365](/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell).
- Graph REST API. See [Assign license](/graph/api/user-assignlicense).
```

2022-10-12 12:06 UTC, JohanFreelancer9 requested changes
Copy review - @kmsft, kindly commit the suggested changes. Many thanks.

2022-10-13 09:29 UTC, JohanFreelancer9 approved these changes

2022-10-13 18:41 UTC, ErikjeMS commented
#sign-off

2022-10-24 19:02 UTC, closed without merging