Update remote-help.md
MicrosoftDocs/memdocs pull request #3233
Opened 2022-10-12 08:10 UTC by msbemba

Request to revert the previous update as the customer claims remote help is still not available on GCC.

@Smritib17  Request to review and update the proposed changes

2022-10-12 08:10 UTC, msbemba commented
@JohanFreelancer9 Please copy review

Issue#https://github.com/MicrosoftDocs/memdocs/issues/3199

2022-10-12 10:04 UTC, JohanFreelancer9 commented on memdocs/intune/remote-actions/remote-help.md
> +> - Remote help is not supported on GCC, GCC High or DoD Tenants.
```suggestion
> - Remote help is not supported on GCC, GCC High, or DoD Tenants.
```

2022-10-12 10:04 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-12 13:29 UTC, JohanFreelancer9 approved these changes

2022-10-13 13:45 UTC, yogkumgit commented
@Smritib17 Please review and signoff this PR. Thanks

2022-11-10 20:13 UTC, Smritib17 commented
@yogkumgit this item has been addressed in https://github.com/MicrosoftDocs/memdocs-pr/pull/9036
Lets close this issue

2022-11-14 13:33 UTC, closed without merging