Explanations and the wordings create confusions
MicrosoftDocs/memdocs pull request #3249
Opened 2022-10-14 06:08 UTC by VigneshMitsume

In the current version, the word "User affinity" and the "Shared device enrollment" etc brings unwanted confusion to the user. Hence i believe these wordings will be more appropriate or close to what we really expect to reflect here to the users.

2022-10-14 07:26 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/device-limit-intune-azure.md
>  Azure device limit restrictions set the maximum number of devices that either Azure AD joins or Azure AD registers. To set the **Maximum number of devices per user**, go to the Azure portal > **Azure
```suggestion
Azure device limit restrictions set the maximum number of devices that either Azure AD joins or Azure AD registers. To set the **Maximum number of devices per user**, go to the Azure portal > **Azure Active Directory** > **Devices**. For more information, see [Configure device settings](/azure/active-directory/devices/device-management-azure-portal).
```

2022-10-14 07:28 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/device-limit-intune-azure.md
> +If you have both Intune and Azure device limit restrictions set, the following table shows you what is applied based on the action triggered by user or not (Referred as user affinity which is differe
```suggestion
If you have both Intune and Azure device limit restrictions set, the following table shows you what is applied based on the action triggered or not triggered by the user (referred to as user affinity, which is different from other documents).
```

2022-10-14 07:28 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/device-limit-intune-azure.md
> +- The Intune **Device limit** setting is set to 2
```suggestion
- The Intune **Device limit** setting is set to 2.
```

2022-10-14 07:32 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/device-limit-intune-azure.md
> +You can't enforce device limit restrictions for these enrollment types because the intune enrollment is triggered either automatically or by the administrator. You can set hard limits for these enrol
```suggestion
You can't enforce device limit restrictions for these enrollment types because Intune enrollment is triggered either automatically or by the administrator. You can set hard limits for these enrollment types in Azure Active Directory.
```

2022-10-14 07:34 UTC, JohanFreelancer9 requested changes
Copy review - @VigneshMitsume, kindly commit the suggested changes. Many thanks.

2022-11-01 20:25 UTC, lenewsad commented
Hi @VigneshMitsume, I checked with the product team and as of now, the edits in lines 55 through 58 are not neccessary. I confirmed that the phrase _user affinity_ is being used here in the same way as other docs, to mean that there are primary users associated with the devices, as opposed to shared devices which don't have user affinity.

2022-11-29 23:53 UTC, lenewsad commented
Hi @VigneshMitsume, thanks for your patience. I added your changes in a separate PR.  Here is what I added:

- Changed "control" to "enroll"
- Changed the content from line 105 to line 108 to say: 
     - " Devices enrolled via these methods are enrolled automatically or by an Intune admin, not by an employee or student, and are considered shared devices.  Instead, you can set a hard limit in Azure Active Directory to limit the number of devices that an employee can join or register with Azure AD."   

We're going to keep the rest as-is for now but I opened an internal task to review and update this article.

2022-11-29 23:53 UTC, closed without merging