Update security-guidelines.md
MicrosoftDocs/memdocs pull request #3258
Opened 2022-10-14 09:26 UTC by kmsft

Added info on Windows Autopatch.

2022-10-17 04:52 UTC, JohanFreelancer9 commented on windows-365/enterprise/security-guidelines.md
> +1. Apply Conditional Access policies to control the devices and apps that can connect to your email and company resources. Use Conditional Access to secure access end user access to Windows 365. Spec
```suggestion
1. Apply Conditional Access policies to control the devices and apps that can connect to your email and company resources. Use Conditional Access to secure end-user access to Windows 365. Specifically, consider using Azure Active Directory (Azure AD) Multi-Factor Authentication to authenticate users. For more information, see [What is Conditional Access in Azure Active Directory?](/azure/active-directory/conditional-access/overview) and how to use [Conditional Access to require Multi-Factor Authentication](/azure/active-directory/conditional-access/howto-conditional-access-policy-all-users-mfa).
```

2022-10-17 04:56 UTC, JohanFreelancer9 commented on windows-365/enterprise/security-guidelines.md
> +   - **Windows Autopatch** is a cloud service that automates updates for Windows, Microsoft 365 Apps for enterprise, Microsoft Edge, and Microsoft Teams on both physical and virtual devices. For more
```suggestion
4. One of the most important elements of device security is OS updates. These updates make sure that devices stay up-to-date and secure while delivering new features and defenses against vulnerabilities. For cloud PCs, options include:
   - **Windows Autopatch** is a cloud service that automates updates for Windows, Microsoft 365 Apps for Enterprise, Microsoft Edge, and Microsoft Teams on both physical and virtual devices. For more information, see [What is Windows Autopatch?](/windows/deployment/windows-autopatch/overview/windows-autopatch-overview) and the [Windows Autopatch FAQ](https://go.microsoft.com/fwlink/?linkid=2200228). Tor turn on Windows Autopatch, [edit your provisioning policy](/windows-365/enterprise/edit-provisioning-policy).
```

2022-10-17 05:06 UTC, JohanFreelancer9 commented on windows-365/enterprise/security-guidelines.md
> +   - **Windows Autopatch** is a cloud service that automates updates for Windows, Microsoft 365 Apps for enterprise, Microsoft Edge, and Microsoft Teams on both physical and virtual devices. For more
```suggestion
   - **Windows Autopatch** is a cloud service that automates updates for Windows, Microsoft 365 Apps for Enterprise, Microsoft Edge, and Microsoft Teams on both physical and virtual devices. For more information, see [What is Windows Autopatch?](/windows/deployment/windows-autopatch/overview/windows-autopatch-overview) and the [Windows Autopatch FAQ](https://go.microsoft.com/fwlink/?linkid=2200228). Tor turn on Windows Autopatch, [edit your provisioning policy](/windows-365/enterprise/edit-provisioning-policy)
```

2022-10-17 05:07 UTC, JohanFreelancer9 commented on windows-365/enterprise/security-guidelines.md
> +7. Windows 365 integrates with Microsoft Defender for Endpoint. Security and endpoint admins can work together to manage their Cloud PC environment just like they manage a physical endpoint. If subsc
```suggestion
6. By default, in Windows 365 Enterprise end users aren't administrators of their cloud PCs. This policy aligns with Windows 10/11 security guidance. For more information about this guidance, see [Local Accounts](/windows/security/identity-protection/access-control/local-accounts#sec-restrict-protect-accounts).
7. Windows 365 integrates with Microsoft Defender for Endpoint. Security and endpoint admins can work together to manage their cloud PC environment just like they manage a physical endpoint. If subscribed, cloud PCs will:
```

2022-10-17 05:08 UTC, JohanFreelancer9 commented on windows-365/enterprise/security-guidelines.md
> +6. By default Windows 365 Enterprise, end users aren't administrators of their Cloud PCs. This policy aligns with Windows 10/11 security guidance. For more information about this guidance, see [Local
```suggestion
6. By default, in Windows 365 Enterprise end users aren't administrators of their Cloud PCs. This policy aligns with Windows 10/11 security guidance. For more information about this guidance, see [Local Accounts](/windows/security/identity-protection/access-control/local-accounts#sec-restrict-protect-accounts).
```

2022-10-17 05:10 UTC, JohanFreelancer9 requested changes
Copy review - @kmsft, kindly commit the suggested changes. Many thanks.

2022-10-17 07:28 UTC, JohanFreelancer9 approved these changes

2022-10-24 19:06 UTC, ErikjeMS commented
@kmsft Please recreate this PR in the private repo. Closing.

2022-10-24 19:06 UTC, closed without merging