Update deploy-security-baselines.md
MicrosoftDocs/memdocs pull request #3260
Opened 2022-10-14 09:42 UTC by kmsft

updated dates, names and versions.  Bug has been filed with @bchopraMSFT that W365 "Preview" tag should be removed

![image](https://user-images.githubusercontent.com/26374704/195816130-38ad4a1d-349f-47ba-85c2-c0ab9e4e31d7.png)

2022-10-17 01:37 UTC, bchopraMSFT approved these changes

2022-10-17 05:38 UTC, JohanFreelancer9 commented on windows-365/enterprise/deploy-security-baselines.md
> +- Windows 365 Security Baseline: November 2021 (Windows 10 or later)
```suggestion
- Windows 365 Security Baseline: November 2021 (Windows 10 and later)
```

2022-10-17 05:39 UTC, JohanFreelancer9 requested changes
Copy review - @kmsft, kindly commit the minor suggested change. Many thanks.

2022-10-24 19:04 UTC, ErikjeMS commented
@kmsft Please recreate this PR in the private repo. Closing.

2022-10-24 19:04 UTC, closed without merging