Update manage-rdp-device-redirections.md
MicrosoftDocs/memdocs pull request #3268
Opened 2022-10-17 05:53 UTC by kmsft

Updated with Nov 2021 version (1 year newer) of the spreadsheet

2022-10-17 05:57 UTC, kmsft reviewed
added win11 links

2022-10-17 09:19 UTC, JohanFreelancer9 commented on windows-365/enterprise/manage-rdp-device-redirections.md
> +To manage any of the redirections by using GPO, create and assign a GPO in your Windows Server Active Directory domain. Make sure to use the corresponding policies as shown in the [RDP device redirec
```suggestion
To manage any of the redirections by using GPO, create and assign a GPO in your Windows Server Active Directory domain. Make sure to use the corresponding policies as shown in the [RDP device redirection settings table](#rdp-device-redirection-settings). To learn more about the policies, download the [Group Policy Settings Reference Spreadsheet for Windows 10 November 2021 Update [21H2]](https://www.microsoft.com/download/103668) and [Group Policy Settings Reference Spreadsheet for Windows 11 2022 [22H2]](https://www.microsoft.com/download/104594).
```

2022-10-17 09:20 UTC, JohanFreelancer9 requested changes
Copy review - @kmsft , kindly commit the suggested change. Many thanks.

2022-10-18 09:23 UTC, JohanFreelancer9 approved these changes

2022-10-24 19:06 UTC, ErikjeMS commented
@kmsft Please recreate this PR in the private repo. Closing.

2022-10-24 19:06 UTC, closed without merging