Update store-apps-company-portal-app.md
MicrosoftDocs/memdocs pull request #3322
Opened 2022-10-29 13:04 UTC by msbemba

Made two changes to reflect offline apps as LOB apps

2022-10-29 13:04 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/memdocs/issues/3314

2022-10-29 13:04 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-10-31 06:11 UTC, JohanFreelancer9 commented on memdocs/intune/apps/store-apps-company-portal-app.md
> +In this document, offline apps are referred to as offline apps because they are Microsoft Store for business use, but offline apps are Line-of-business (LOB) apps.
```suggestion
In this document, offline apps are referred to as offline apps because they are for Microsoft Store for Business use, but offline apps are Line-of-business (LOB) apps.
```

2022-10-31 06:12 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-31 13:20 UTC, JohanFreelancer9 approved these changes

2022-11-30 22:51 UTC, Erikre commented
Offline apps are managed by Intune, whereas online apps are managed by the store. Use offline apps when you need to install and maintain a specific app version. A line-of-business (LOB) app is an app that you add to Intune from an app installation file. This kind of app is typically written in-house. 

@msbemba - Based on the above, I'm closing this PR. Let me know if you think we should re-open. Thanks

2022-11-30 22:51 UTC, closed without merging