Update defender-advanced-threat-protection.md
MicrosoftDocs/memdocs pull request #3389
Opened 2022-11-25 21:34 UTC by baardhermansen

Updated with new URL for Defender portal in several locations. 
Updated instructions for on- and offboarding according to the new portal.  
Other smaller markdown corrections, like removing extra spaces between list items.

2022-11-26 05:59 UTC, JohanFreelancer9 commented on memdocs/configmgr/protect/deploy-use/defender-advanced-threat-protection.md
>  1. For **Microsoft Defender for Endpoint Client on Windows Server 2012 R2 and Windows Server 2016** setting, The default value is set as **Microsoft Monitoring Agent (legacy)** which needs to be chan
```suggestion
1. Create custom Client Device Settings or go to the properties of the required client setting and select **Endpoint Protection**.
1. For **Microsoft Defender for Endpoint Client on Windows Server 2012 R2 and Windows Server 2016** setting, the default value is set as **Microsoft Monitoring Agent (legacy)** which needs to be changed to **MDE Client (recommended)**.
```

2022-11-26 05:59 UTC, JohanFreelancer9 commented on memdocs/configmgr/protect/deploy-use/defender-advanced-threat-protection.md
> +
```suggestion
```

2022-11-26 06:00 UTC, JohanFreelancer9 commented on memdocs/configmgr/protect/deploy-use/defender-advanced-threat-protection.md
> +1. Change the operating system to either **Windows 7 SP1 and 8.1** or **Windows Server 2008 R2 Sp1** from the list.
```suggestion

1. Change the operating system to either **Windows 7 SP1 and 8.1** or **Windows Server 2008 R2 Sp1** from the list.
```

2022-11-26 06:00 UTC, JohanFreelancer9 commented on memdocs/configmgr/protect/deploy-use/defender-advanced-threat-protection.md
> +1. In the Configuration Manager console, navigate **Monitoring** > **Security** and then select **Microsoft Defender ATP**.
```suggestion
1. In the Configuration Manager console, navigate to **Monitoring** > **Security** and then select **Microsoft Defender ATP**.
```

2022-11-26 06:00 UTC, JohanFreelancer9 commented on memdocs/configmgr/protect/deploy-use/defender-advanced-threat-protection.md
> +        - **Not onboarded** - Policy was applied but the agent hasn't reported policy onboard
```suggestion
    - **Microsoft Defender ATP Agent Onboarding Status**: The number and percentage of eligible managed client computers with active Microsoft Defender for Endpoint policy onboarded.
    - **Microsoft Defender ATP Agent Health**: Percentage of computer clients reporting status for their Microsoft Defender for Endpoint agent:
        - **Healthy** - Working properly.
        - **Inactive** - No data sent to service during time period.
        - **Agent state** - The system service for the agent in Windows isn't running.
        - **Not onboarded** - Policy was applied but the agent hasn't reported policy onboard.
```

2022-11-26 06:09 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-27 19:33 UTC, baardhermansen commented on memdocs/configmgr/protect/deploy-use/defender-advanced-threat-protection.md
> +
Hi @JohanFreelancer9 
Wouldn't your suggestion break with rule regarding headings?
[Rule MD022](https://github.com/DavidAnson/markdownlint/blob/v0.26.2/doc/Rules.md#md022)

2022-11-27 19:33 UTC, baardhermansen commented on memdocs/configmgr/protect/deploy-use/defender-advanced-threat-protection.md
> +1. Change the operating system to either **Windows 7 SP1 and 8.1** or **Windows Server 2008 R2 Sp1** from the list.
Sorry, but i don't see how this is beneficial? The step belongs to the ones above, not as a separate list?

2022-11-28 01:31 UTC, BalaDelli commented
#sign-off

2022-11-28 06:32 UTC, JohanFreelancer9 commented on memdocs/configmgr/protect/deploy-use/defender-advanced-threat-protection.md
> +
@baardhermansen, only one blank line is needed around the headings. If we don't remove the blank line as suggested, there will be two blank lines (lines 227 and 228, whereas only one is required.

2022-11-28 06:34 UTC, JohanFreelancer9 commented on memdocs/configmgr/protect/deploy-use/defender-advanced-threat-protection.md
> +1. Change the operating system to either **Windows 7 SP1 and 8.1** or **Windows Server 2008 R2 Sp1** from the list.
Hi @baardhermansen, yes you are correct. I apologize, my mistake. I'll remove the suggestion. Many thanks.

2022-11-30 18:27 UTC, baardhermansen commented on memdocs/configmgr/protect/deploy-use/defender-advanced-threat-protection.md
> +
@JohanFreelancer9  Aha, i misread the diff...

2022-12-01 08:41 UTC, JohanFreelancer9 approved these changes

2023-10-20 18:38 UTC, baardhermansen commented
Ping @BalaDelli for a review.

2023-10-27 15:40 UTC, BalaDelli approved these changes

2023-10-27 15:41 UTC, BalaDelli commented
#sign-off

2024-11-24 18:52 UTC, closed without merging