Update windows-autopilot-hybrid.md
MicrosoftDocs/memdocs pull request #3390
Opened 2022-11-26 08:01 UTC by JuanitaBaptiste

updating adfs impact

2022-11-28 07:27 UTC, JohanFreelancer9 commented on memdocs/autopilot/windows-autopilot-hybrid.md
> +Although not required, configuring hybrid azure AD join for ADFS enables a faster Autopilot AAD registration process during deployments.
```suggestion
Although not required, configuring hybrid Azure AD join for AD FS enables a faster Windows Autopilot Azure AD registration process during deployments. 
```

2022-11-28 07:28 UTC, JohanFreelancer9 requested changes
Copy review - @JuanitaBaptiste, kindly commit the suggested changes. Many thanks.

2022-11-28 09:25 UTC, JohanFreelancer9 approved these changes

2022-12-01 14:56 UTC, frankroj commented
Approving changes

2022-12-01 14:56 UTC, frankroj commented
#sign-off

2022-12-01 15:00 UTC, frankroj approved these changes

2022-12-01 15:02 UTC, frankroj commented
#sign-off

2022-12-01 21:30 UTC, merged