Update registration-auth.md
MicrosoftDocs/memdocs pull request #3391
Opened 2022-11-26 08:29 UTC by JuanitaBaptiste

updated to Microsoft admin center

2022-11-28 07:31 UTC, JohanFreelancer9 commented on memdocs/autopilot/registration-auth.md
> +2. Customer logs into the Microsoft Admin Center using a cloud native account (example: [domain].onmicrosoft.com) with global administrator privileges.
```suggestion
2. Customer logs into Microsoft admin center using a cloud-native account (for example, [domain].onmicrosoft.com) with Global administrator privileges.
```

2022-11-28 07:32 UTC, JohanFreelancer9 commented on memdocs/autopilot/registration-auth.md
> +3. Clicks the link in the email, which takes them directly to the following page:
```suggestion
3. Selects the link in the email, which takes them directly to the following page:
```

2022-11-28 07:33 UTC, JohanFreelancer9 requested changes
Copy review - @JuanitaBaptiste, kindly commit the suggested changes. Many thanks.

2022-11-28 09:30 UTC, JohanFreelancer9 requested changes
@JuanitaBaptiste, you seem to have missed one suggested change. Could you also commit that, please?

2022-11-29 09:45 UTC, JohanFreelancer9 approved these changes

2022-11-29 09:45 UTC, JohanFreelancer9 approved these changes

2022-12-07 00:58 UTC, frankroj commented
Reached out to contributor to clarify which admin center they are referring to in the change. Also inquired if a change in screen shots may be necessary.

2022-12-27 21:06 UTC, traya1 commented
Learn Build status updates of commit _[2cd10c2](https://github.com/JuanitaBaptiste/memdocs/commits/2cd10c2daec440d8d474a718b434f7955d461c03)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[memdocs/autopilot/registration-auth.md](https://github.com/JuanitaBaptiste/memdocs/blob/patch-6/memdocs/autopilot/registration-auth.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/aa268e4d-aaaf-30c8-4118-35d62ca794c9/202212272105201992-3391/BuildReport?accessString=323796b416de04485df12a3a338a7d4ca8019e9d0814b814f9d74ab2334a2d77).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/aa268e4d-aaaf-30c8-4118-35d62ca794c9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-27 21:07 UTC, frankroj commented
Approving changes. Need to update graphics but I will do that in a separate PR

2022-12-27 21:07 UTC, frankroj commented
#sign-off

2022-12-27 21:07 UTC, merged