Update deployment-guide-enrollment-mamwe.md
MicrosoftDocs/memdocs pull request #3407
Opened 2022-11-30 15:40 UTC by msbemba

Added a statement that MAM is deprecated and  After December 2022 customers will not be able to configure any new WIP policies for devices registered via MEM without enrollment.

reference #https://techcommunity.microsoft.com/t5/windows-it-pro-blog/announcing-the-sunset-of-windows-information-protection-wip/ba-p/3579282

fixes #https://github.com/MicrosoftDocs/memdocs/issues/3365

2022-11-30 15:40 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-12-01 10:16 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/deployment-guide-enrollment-mamwe.md
> +> Mobile Application Management (MAM) is deprecated for Windows. After December 2022 customers will not be able to configure any new WIP policies for devices registered via MEM without enrollment. Th
```suggestion
> Mobile Application Management (MAM) is deprecated for Windows. After December 2022 customers will not be able to configure any new Microsoft Information Protection (WIP) policies for devices registered via MAM without enrollment. This does not apply to devices enrolled in MAM.
```

2022-12-01 10:16 UTC, JohanFreelancer9 requested changes
Copy review.

2022-12-01 11:59 UTC, JohanFreelancer9 approved these changes

2022-12-01 12:24 UTC, yogkumgit commented
@MandiOhlinger Please review and signoff this PR. Thanks

2023-01-19 14:11 UTC, yogkumgit commented
@MandiOhlinger Kindly update. Thanks

2023-06-14 15:17 UTC, MandiOhlinger approved these changes

2023-06-14 15:23 UTC, MandiOhlinger approved these changes

2023-06-14 15:24 UTC, merged

2023-06-14 15:24 UTC, MandiOhlinger commented
@msbemba Thank you for making these changes. I made some other changes too. The PR is now merged.