Update troubleshoot.md
MicrosoftDocs/memdocs pull request #3471
Opened 2022-12-21 15:50 UTC by andrewjohnporter

Wanted to make it clearer that the account used to log into MEM is the account that needs permissions in SCCM.

Also adding information for fixing a unhealthy Connector when setting up Tenant Attach fails

2022-12-21 15:51 UTC, traya1 commented
Learn Build status updates of commit _[b7073e2](https://github.com/andrewjohnporter/memdocs/commits/b7073e22f6f13034d7a89d2d1107071a97f50b07)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[memdocs/configmgr/tenant-attach/troubleshoot.md](https://github.com/andrewjohnporter/memdocs/blob/patch-4/memdocs/configmgr/tenant-attach/troubleshoot.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/aa268e4d-aaaf-30c8-4118-35d62ca794c9/202212211550213086-3471/BuildReport?accessString=79c82f6ab3fbfedefb6db03d10bfa5c7b33a570e817e86a81ed2a61ff228bed3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/aa268e4d-aaaf-30c8-4118-35d62ca794c9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-22 04:15 UTC, JohanFreelancer9 commented on memdocs/configmgr/tenant-attach/troubleshoot.md
> +If the account that is logged into the Endpoint Admin Center doesn't have the required permissions in Configuration Manager, you'll see an `Unauthorized` response in the **CMGatewayNotificationWorker
```suggestion
If the account that is logged into the Endpoint Manager admin center does not have the required permissions in Configuration Manager, you'll see an `Unauthorized` response in the **CMGatewayNotificationWorker.log**.
```

2022-12-22 04:15 UTC, JohanFreelancer9 commented on memdocs/configmgr/tenant-attach/troubleshoot.md
> +When you view the Microsoft Endpoint Configuration Maanger Connector in the Endpoint Admin Center > **Tenant Administration** > **Connectors and tokens** and it is showing as unhealthy or unknown you
```suggestion
When you view the Microsoft Endpoint Configuration Manager connector in the Endpoint Manager admin center > **Tenant Administration** > **Connectors and tokens** and it shows as unhealthy or unknown, you could delete the connector to attempt to resolve the issue. You will need to wait a couple of hours for the connector to be deleted and for a new connector to be created automatically. Do not change any of the Tenant Attach configurations in the Configuration Manager console.
```

2022-12-22 04:17 UTC, JohanFreelancer9 requested changes
Copy review - @andrewjohnporter, kindly commit the suggested changes. Many thanks.

2022-12-22 04:38 UTC, Banreet approved these changes

2022-12-22 07:56 UTC, andrewjohnporter commented
thanks. Happy with those.

2022-12-22 07:57 UTC, andrewjohnporter reviewed
good for me

2022-12-22 07:58 UTC, andrewjohnporter commented on memdocs/configmgr/tenant-attach/troubleshoot.md
> +When you view the Microsoft Endpoint Configuration Maanger Connector in the Endpoint Admin Center > **Tenant Administration** > **Connectors and tokens** and it is showing as unhealthy or unknown you
good for me

2022-12-22 07:59 UTC, traya1 commented
Learn Build status updates of commit _[b7073e2](https://github.com/andrewjohnporter/memdocs/commits/b7073e22f6f13034d7a89d2d1107071a97f50b07)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[memdocs/configmgr/tenant-attach/troubleshoot.md](https://github.com/andrewjohnporter/memdocs/blob/patch-4/memdocs/configmgr/tenant-attach/troubleshoot.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/aa268e4d-aaaf-30c8-4118-35d62ca794c9/202212220757433805-3471/BuildReport?accessString=6eb1e1ef70818ce33efc6f0b06ed1a3562a718647c079a55bdba66145f3dee82).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/aa268e4d-aaaf-30c8-4118-35d62ca794c9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2025-12-10 16:14 UTC, MandiOhlinger commented
@andrewjohnporter Hey Andrew - This PR has a merge conflict. If it's still needed, can you create a new pull request? We want to make sure you get credit for the doc change.

2026-04-14 15:49 UTC, Yupiter2005 commented
@andrewjohnporter , let me implement your change via my own PR. I've removed the second part, since there are some "ifs" that a better to be attended via support ticket.

Closing this PR then and thanks for your contribution!

2026-04-14 15:49 UTC, closed without merging