Updated enrollments that support notifications
MicrosoftDocs/memdocs pull request #3473
Opened 2022-12-21 23:51 UTC by maholdaa

Added details to which enrollment types are and are not supported based on feedback

2022-12-21 23:52 UTC, traya1 commented
Learn Build status updates of commit _[bb32f48](https://github.com/maholdaa/memdocs/commits/bb32f4867f18f6fddcdc691eee7a10d7ad57c949)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[memdocs/intune/enrollment/enrollment-notifications.md](https://github.com/maholdaa/memdocs/blob/patch-3/memdocs/intune/enrollment/enrollment-notifications.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/aa268e4d-aaaf-30c8-4118-35d62ca794c9/202212212351196015-3473/BuildReport?accessString=6a55dcc87d70ed124591acdcda80d3b17d522f01861e2a5979afa7cc599252d0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/aa268e4d-aaaf-30c8-4118-35d62ca794c9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-17 18:18 UTC, lenewsad requested changes
Hi @maholdaa, thanks for your contribution. What does the "DEP" acronym next to Android stand for?

2023-01-19 09:23 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/enrollment-notifications.md
> +* Windows 10/11 (excludes hybrid AADJ)
```suggestion
* Windows 10/11 (excludes hybrid Azure AD-joined devices)
```

2023-01-19 09:24 UTC, JohanFreelancer9 requested changes
Copy review - @maholdaa, kindly commit the suggested change and expand the acronyms DEP and ADE.

2023-01-27 19:53 UTC, lenewsad commented
Hi @maholdaa, following up. There isn't a "DEP" associated w/Android. Can you please expand on what you mean by that acronym? 

For IOS, are we still supporting enrollments set up through "DEP" or were all customers required to upgrade to Apple Business Manager and Apple School Manager? source: https://support.apple.com/en-us/HT209617

2023-02-07 11:05 UTC, yogkumgit commented
@maholdaa Gentle reminder. Thanks

2023-02-07 12:13 UTC, JohanFreelancer9 approved these changes

2023-02-08 01:19 UTC, maholdaa commented
@lenewsad sorry Laura seeing this now --- maybe instead we can rephrase -- right now for both Apple and Android platform enrollment notifications work for BYOD or personally enrolled scenarios.

2023-02-10 16:33 UTC, lenewsad commented
Thanks for confirming @maholdaa!

2023-02-10 16:35 UTC, lenewsad commented
#sign-off

2023-02-10 16:36 UTC, lenewsad approved these changes

2023-02-10 16:36 UTC, lenewsad commented
#sign-off

2023-02-13 17:12 UTC, merged