Update microsoft-tunnel-configure.md
MicrosoftDocs/memdocs pull request #3500
Opened 2023-01-10 19:23 UTC by msbemba

added a note that PAC proxies are only supported by Microsoft Edge on Android at the moment.

fixes#https://github.com/MicrosoftDocs/memdocs/issues/3485

2023-01-10 19:23 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-01-10 19:25 UTC, traya1 commented
Learn Build status updates of commit _[f91ba0f](https://github.com/msbemba/memdocs/commits/f91ba0f97af639f2c6a469e87a9fe3f74523d907)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[memdocs/intune/protect/microsoft-tunnel-configure.md](https://github.com/msbemba/memdocs/blob/patch-189/memdocs/intune/protect/microsoft-tunnel-configure.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/aa268e4d-aaaf-30c8-4118-35d62ca794c9/202301101923193790-3500/BuildReport?accessString=e5442d9982bd480e10356031db8cacd2d5c024f7767870e5ecca751ffd14701a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/aa268e4d-aaaf-30c8-4118-35d62ca794c9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-11 03:47 UTC, JohanFreelancer9 commented on memdocs/intune/protect/microsoft-tunnel-configure.md
> +> Proxy Auto-Configuration is supported by Microsoft Edge on Android at the moment. Applications such as Android System WebView, only support proxy host/ip and port.
```suggestion
> Proxy Auto-Configuration is supported by Microsoft Edge on Android at the moment. Applications such as Android System WebView, only support proxy host/IP and port.
```

2023-01-11 03:47 UTC, JohanFreelancer9 requested changes
Copy review.

2023-01-11 09:43 UTC, JohanFreelancer9 approved these changes

2023-01-12 23:27 UTC, Brenduns commented
@msbemba  - I've consulted with the development team on this PR, and we are not able to accept it. The general idea is OK, but the developers are aware of some complications involved with this statement for the Android _System WebView_ that need to be properly reviewed, researched,  and then surfaced with more in depth guidance before we add this type of information. Its unfortunately not as simple as the GitHub issues suggestion/request makes this out to be. 

There is no ETA on this work, as its not deemed urgent, but it will be active work that will eventually drive a more full-fledged statement.

2023-01-12 23:27 UTC, closed without merging