Add note about MS Edge requirements
MicrosoftDocs/memdocs pull request #3503
Opened 2023-01-11 22:28 UTC by AndreyTretyak

MS Edge needs to be started at least once for MS Intune to work properly. This took me some time to figure it out, so adding it in the docs to save other troubles. Feel free to change my wording if there is a better way to express this.

2023-01-12 07:23 UTC, JohanFreelancer9 commented on memdocs/intune/user-help/enroll-device-linux.md
> +1. Open Microsoft Edge. It needs to run at least once after install to initalize componetns that would be used by Microsoft Intune.
```suggestion
1. Open Microsoft Edge. It needs to run at least once after installation to initialize components that would be used by Microsoft Intune.
```

2023-01-12 07:25 UTC, JohanFreelancer9 requested changes
Copy review - @AndreyTretyak, kindly commit the suggested changes. Many thanks.

2023-01-13 09:04 UTC, JohanFreelancer9 approved these changes

2023-01-16 14:09 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks.

2023-01-17 18:21 UTC, tiburd commented
@lenewsad 
Hi Laura,
Can you please review these changes?
Thanks!

2023-01-17 18:23 UTC, lenewsad commented
Hi @yogkumgit @tiburd @AndreyTretyak, waiting for PM review.

2023-01-17 18:46 UTC, benferse commented
Starting Edge is not a requirement for the Intune app to function properly. We have test environments for Intune that don't even install Edge. It sounds like there is something else specific to your environment @AndreyTretyak that is going on - if this is reproducible can you contact support to investigate further?

2023-01-17 19:34 UTC, AndreyTretyak commented
> Starting Edge is not a requirement for the Intune app to function properly. We have test environments for Intune that don't even install Edge. It sounds like there is something else specific to your environment @AndreyTretyak Andrey Tretyak FTE that is going on - if this is reproducible can you contact support to investigate further?

@benferse  thank you for the response. 
Just out of curiosity, have you tried it with accounts that require 2FA? In my case three separate Ubuntu VMs (22 and 20) were showing blank windows instead of 2FA screen until I've installed and started MS Edge.
What would be the best way to contact support about this?

2023-01-24 20:09 UTC, lenewsad commented
Hi @AndreyTretyak, There are a couple of support options available: 

- Post to [Microsoft Intune forums](https://docs.microsoft.com/answers/products/mem) on Microsoft Q & A. This space is moderated by our community MVPs who are very experienced, knowledgeable, and helpful. 

- Use [Microsoft Support for business](https://aka.ms/cmcbsupport) to search for an issue, or open a case with professional support. 

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager. 

  FYI @benferse

2023-01-27 19:43 UTC, lenewsad commented
Thanks again @AndreyTretyak for reaching out to the Docs team. I'm going to close this PR since we determined that no changes are needed. Please don't hesitate to open more PRs with us in the future--we're happy to review them.

2023-01-27 19:43 UTC, closed without merging