Updates to Intune iOS MAM SDK dev guide
MicrosoftDocs/memdocs pull request #3545
Opened 2023-01-27 15:53 UTC by Kyle-Reis

Removing obsolete instructions on stripping out simulator architectures. Removing information on DebugSettingsEnabled flag that is not supported for 3rd party/LOB apps. Adding info on app intents.

2023-01-28 10:31 UTC, JohanFreelancer9 commented on memdocs/intune/developer/app-sdk-ios.md
>      :::image type="content" source="media/app-sdk-ios/intune-app-sdk-ios-linked-static-lib.png" alt-text="Intune App SDK iOS Static Library: Xcode Frameworks, Libraries, and Embedded Content sample":
```suggestion

        :::image type="content" source="media/app-sdk-ios/intune-app-sdk-ios-linked-static-lib.png" alt-text="Intune App SDK iOS Static Library: Xcode Frameworks, Libraries, and Embedded Content sample":::
```

2023-01-28 10:32 UTC, JohanFreelancer9 requested changes
Copy review - @Kyle-Reis, kindly commit the minor suggested change. Many thanks.

2023-01-30 12:36 UTC, yogkumgit commented
@Kyle-Reis Gentle reminder. Thanks

2023-01-30 15:41 UTC, JohanFreelancer9 approved these changes

2023-01-31 13:29 UTC, yogkumgit commented
@Erikre Please signoff this PR. Thanks

2023-02-24 23:00 UTC, Erikre approved these changes

2023-02-24 23:00 UTC, Erikre commented
#sign-off

2023-02-26 06:41 UTC, yogkumgit commented
@tiburd Please merge this Pr. Thanks

2023-02-27 15:18 UTC, merged