Update enroll-device-linux.md
MicrosoftDocs/memdocs pull request #3569
Opened 2023-02-05 00:07 UTC by msbemba

added a note that ubuntu on wsl2 is not supported.

reference - https://learn.microsoft.com/en-us/windows/wsl/enterprise

fixes#https://github.com/MicrosoftDocs/memdocs/issues/3554

2023-02-05 00:07 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-02-05 05:31 UTC, JohanFreelancer9 commented on memdocs/intune/user-help/enroll-device-linux.md
> +> Ubuntu on WSL2 is not a supported scenario and the requests is in on our backlog and we are investigating ways to add them.
```suggestion
> Currently, Ubuntu on WSL2 is not supported but we are investigating ways to add support for it in the future..
```

2023-02-05 05:34 UTC, JohanFreelancer9 requested changes
Copy review.

2023-02-05 12:41 UTC, rovinbhandari approved these changes

2023-02-05 15:18 UTC, JohanFreelancer9 approved these changes

2023-02-06 13:13 UTC, yogkumgit commented
@lenewsad Please signoff this PR. Thanks

2023-02-08 02:32 UTC, lenewsad commented
Hi @msbemba @yogkumgit, thanks for the ping. Waiting on PM to approve change.

2023-02-10 16:19 UTC, lenewsad commented
Hi @msbemba and @yogkumgit, thank you for working through this PR. Confirmed w/PM that it's not currently supported but no word on plans for future support, so I removed that part.

2023-02-10 16:19 UTC, lenewsad commented
#sign-off

2023-02-10 23:17 UTC, lenewsad approved these changes

2023-02-13 12:06 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-02-13 17:11 UTC, merged