Update quickstart-setup-auto-enrollment.md
MicrosoftDocs/memdocs pull request #3570
Opened 2023-02-05 00:35 UTC by msbemba

Added the important note to the document stating that For Windows BYOD devices, the MAM user scope takes precedence if both the MAM user scope and the MDM user scope (automatic MDM enrollment) are enabled for all users

fixes#https://github.com/MicrosoftDocs/memdocs/issues/3342

2023-02-05 00:35 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-02-05 05:43 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/quickstart-setup-auto-enrollment.md
> +> For Windows BYOD devices, the MAM user scope takes precedence if both the MAM user scope and the MDM user scope (automatic MDM enrollment) are enabled for all users (or the same groups of users). T
```suggestion
> For Windows BYOD devices, the MAM user scope takes precedence if both the MAM user scope and the MDM user scope (automatic MDM enrollment) are enabled for all users (or the same groups of users). The device will not be MDM enrolled, and Windows Information Protection (WIP) policies will be applied if you have configured them.
```

2023-02-05 05:43 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/quickstart-setup-auto-enrollment.md
> +If your intent is to enable automatic enrollment for Windows BYOD devices to an MDM: configure the MDM user scope to All (or Some, and specify a group) and configure the MAM user scope to None (or So
```suggestion
If your intent is to enable automatic enrollment for Windows BYOD devices to an MDM, configure the MDM user scope to All (or Some, and specify a group) and configure the MAM user scope to None (or Some, and specify a group–ensuring that users are not members of a group targeted by both MDM and MAM user scopes).
```

2023-02-05 05:44 UTC, JohanFreelancer9 requested changes
Copy review.

2023-02-05 15:08 UTC, JohanFreelancer9 approved these changes

2023-02-06 13:12 UTC, yogkumgit commented
@lenewsad Please signoff this PR. Thanks

2023-02-08 02:17 UTC, lenewsad commented
#sign-off

2023-02-08 17:03 UTC, merged