Update in-development.md
MicrosoftDocs/memdocs pull request #3574
Opened 2023-02-06 15:21 UTC by msbemba

Updated the document to reflect that On-demand proactive remediation isn't in Public Preview

fixes#https://github.com/MicrosoftDocs/memdocs/issues/3567

2023-02-06 15:21 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-02-07 02:30 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/in-development.md
> +A new device action that is in Private preview allows you to run a proactive remediation on-demand to a single Windows device. The **Run** remediation device action will allow you to resolve issues w
```suggestion
A new device action that is in private preview allows you to run a proactive remediation on-demand to a single Windows device. The **Run** remediation device action will allow you to resolve issues without having to wait for a proactive remediation to run on its assigned schedule. You will also be able to view the status of proactive remediations under **Remediations** in the **Monitor** section of a device.
```

2023-02-07 02:30 UTC, JohanFreelancer9 requested changes
Copy review.

2023-02-07 09:39 UTC, JohanFreelancer9 approved these changes

2023-02-07 11:07 UTC, yogkumgit commented
@dougeby Please signoff and merge this PR. Thanks

2024-02-07 22:03 UTC, Brenduns commented
Closing without other action.  This PR has long been irrelivent. Subsequent to creation, the feature involved released to public preview making this PR a non-issue.

2024-02-07 22:03 UTC, closed without merging