Update wi-fi-settings-android-enterprise.md
MicrosoftDocs/memdocs pull request #3599
Opened 2023-02-17 15:02 UTC by msbemba

Added a note per recommendation on #https://github.com/MicrosoftDocs/memdocs/issues/3597

Fixes#https://github.com/MicrosoftDocs/memdocs/issues/3597

2023-02-18 06:22 UTC, JohanFreelancer9 commented on memdocs/intune/configuration/wi-fi-settings-android-enterprise.md
> +    > So when  Wi-Fi Profile is pushed for the device, by design Wi-Fi will be made to turn on.
```suggestion
    > When a device is marked **Corporate**, the user has little control, and all control will depend on the policies enforced. So when a Wi-Fi Profile is pushed for the device, Wi-Fi will be turned on by design.
```

2023-02-18 06:22 UTC, JohanFreelancer9 requested changes
Copy review.

2023-02-19 06:08 UTC, yogkumgit commented
@msbemba

2023-02-21 13:59 UTC, MandiOhlinger commented on memdocs/intune/configuration/wi-fi-settings-android-enterprise.md
> +    > So when  Wi-Fi Profile is pushed for the device, by design Wi-Fi will be made to turn on.
This is my suggested change:

> When a device is marked as corporate during enrollment (organization-owned), policies control device features and settings. Users can be prevented from managing features and settings in the policy.
>
> When a Wi-Fi policy is assigned to devices, then Wi-Fi is enabled, and users can be prevented from turning off Wi-Fi.

2023-02-22 13:12 UTC, yogkumgit commented
@JohanFreelancer9

2023-02-22 13:13 UTC, yogkumgit commented
@MandiOhlinger Please review and sign off this PR. Thanks

2023-02-22 14:29 UTC, MandiOhlinger approved these changes

2023-02-22 14:29 UTC, MandiOhlinger commented
#sign-off

2023-02-22 14:29 UTC, JohanFreelancer9 approved these changes

2023-02-23 13:52 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-02-23 15:43 UTC, merged