Add link for custom compliance scripts for Linux hosted on GitHub.
MicrosoftDocs/memdocs pull request #3601
Opened 2023-02-18 01:01 UTC by pmarcone

There are already a few sample scripts for Linux, that may be useful as reference.

2023-02-18 06:07 UTC, JohanFreelancer9 commented on memdocs/intune/protect/compliance-custom-script.md
> +	- [Intune Linux Custom Compliance Samples](https://github.com/microsoft/shell-intune-samples/tree/master/Linux)
```suggestion

- [POSIX Shell Tutorial (grymoire.com)](https://www.grymoire.com/Unix/Sh.html), a third-party website.

	- [Intune Linux Custom Compliance Samples](https://github.com/microsoft/shell-intune-samples/tree/master/Linux).
```

2023-02-18 06:08 UTC, JohanFreelancer9 requested changes
Copy review - @pmarcone, kindly commit the suggested changes. Many thanks.

2023-02-19 10:42 UTC, JohanFreelancer9 approved these changes

2023-02-22 13:12 UTC, yogkumgit commented
@Brenduns Please review and signoff this PR. Thanks

2023-02-22 18:05 UTC, Brenduns commented
Reviewing PR with Dev resources.

2023-03-20 21:08 UTC, Brenduns commented
#sign-off

2023-03-21 12:21 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-03-21 16:56 UTC, merged