Update windows-bulk-enroll.md
MicrosoftDocs/memdocs pull request #3623
Opened 2023-02-27 20:59 UTC by tofergus

Add note to clarify that bulk token requestor must be in AAD MDM user scope

2023-02-28 09:41 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/windows-bulk-enroll.md
> +> The account used to request the bulk token must be included in the [MDM user scope](https://learn.microsoft.com/en-us/mem/intune/enrollment/windows-enroll#enable-windows-automatic-enrollment) that
```suggestion
> The account used to request the bulk token must be included in the [MDM user scope](/mem/intune/enrollment/windows-enroll#enable-windows-automatic-enrollment) that is specified in Azure AD.
```

2023-02-28 09:42 UTC, JohanFreelancer9 requested changes
Copy review - @tofergus, kindly commit the suggested changes. Many thanks.

2023-03-02 22:22 UTC, lenewsad commented
#sign-off

2023-03-03 11:26 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-03-03 16:51 UTC, merged