Update size-and-scale-numbers.md
MicrosoftDocs/memdocs pull request #3635
Opened 2023-03-02 16:23 UTC by rasiddiq

> [!TIP]  
    > Don't install management points on servers that are across a slow link from the primary site server or the site database server. If Management point is not in the same datacenter OR sometimes refer to as Fast link, you can experience latency on state and status messages. If you have requirement of having a remote management point, please consider using Secondary site instead. This will avoid backlog issues for state/status messages.

2023-03-03 06:38 UTC, JohanFreelancer9 commented on memdocs/configmgr/core/plan-design/configs/size-and-scale-numbers.md
> +    > Don't install management points on servers that are across a slow link from the primary site server or the site database server. If Management point is not in the same datacenter OR sometimes r
```suggestion
    > Don't install management points on servers that are across a slow link from the primary site server or the site database server. If the management point is not in the same data center (also referred to as a fast link), you can experience latency on state and status messages. If you have a requirement for a remote management point, consider using a secondary site instead. This will avoid backlog issues for state and status messages.
```

2023-03-03 06:39 UTC, JohanFreelancer9 requested changes
Copy review - @rasiddiq, kindly commit the suggested changes. Many thanks.

2023-03-03 15:08 UTC, JohanFreelancer9 approved these changes

2023-04-04 20:39 UTC, JohanFreelancer9 requested changes
@rasiddiq, one more suggested change, please.

2023-04-05 04:48 UTC, Banreet approved these changes

2023-04-05 04:48 UTC, Banreet commented
#sign-off

2023-04-07 05:32 UTC, JohanFreelancer9 approved these changes

2023-06-19 17:09 UTC, merged