Update create-custom-role.md
MicrosoftDocs/memdocs pull request #3641
Opened 2023-03-03 15:52 UTC by msbemba

Updated view reports on the document

fixes#https://github.com/MicrosoftDocs/memdocs/issues/3577

2023-03-03 15:52 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-03-04 07:06 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/create-custom-role.md
> +|Mobile apps\View reports| View Reports on mobile applications such as store apps, line-of-business apps, web-links or built-in apps. |
```suggestion
|Mobile apps/View reports| View reports on mobile applications such as store apps, line-of-business apps, web links, and built-in apps. |
```

2023-03-04 07:06 UTC, JohanFreelancer9 requested changes
Copy review.

2023-03-04 07:25 UTC, yogkumgit commented
@msbemba

2023-03-05 09:25 UTC, JohanFreelancer9 approved these changes

2023-03-06 11:17 UTC, yogkumgit commented
@Smritib17 Please review and signoff this PR. Thanks

2023-03-09 19:05 UTC, merged

2023-03-09 19:06 UTC, Smritib17 commented
#sign-off