Update endpoint-protection-macos.md
MicrosoftDocs/memdocs pull request #3648
Opened 2023-03-06 15:04 UTC by msbemba

Made changes to Do not allow user to override Gatekeeper

Fixes#https://github.com/MicrosoftDocs/memdocs/issues/3620

2023-03-06 15:05 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-03-06 16:06 UTC, Brenduns commented
#sign-off

2023-03-06 16:07 UTC, JohanFreelancer9 commented on memdocs/intune/protect/endpoint-protection-macos.md
> +  Prevents users from overriding the Gatekeeper setting, and prevents users from Control clicking to install an app. When enabled, users cannot Control-click any app, or install it.
```suggestion
  Prevents users from overriding the Gatekeeper setting, and prevents users from Control-clicking to install an app. When enabled, users cannot Control-click any app, or install it.
```

2023-03-06 16:07 UTC, JohanFreelancer9 requested changes
Copy review.

2023-03-07 07:19 UTC, JohanFreelancer9 commented on memdocs/intune/protect/endpoint-protection-macos.md
> +  Prevents users from overriding the Gatekeeper setting, and prevents users from Control-clicking to install an app. When enabled, users cannot Control-click any app, or install it.
```suggestion
  Prevents users from overriding the Gatekeeper setting, and prevents users from Control-clicking to install an app. When enabled, users cannot Control-click any app to install it.
```

2023-03-07 07:19 UTC, JohanFreelancer9 requested changes
Apologies @msbemba, one more, please.

2023-03-07 11:39 UTC, JohanFreelancer9 approved these changes

2023-03-07 13:13 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-03-07 15:25 UTC, merged