Update turn-off-microsoft-usage-data-collection-windows.md
MicrosoftDocs/memdocs pull request #3649
Opened 2023-03-06 15:22 UTC by msbemba

Added details about what data is being collected.

Fixes#https://github.com/MicrosoftDocs/memdocs/issues/3646

2023-03-06 16:46 UTC, JohanFreelancer9 commented on memdocs/intune/user-help/turn-off-microsoft-usage-data-collection-windows.md
> +For more information on what data is being collected, check [Optional diagnostic data from Intune Client apps](/mem/intune/protect/client-apps-optional-data)
```suggestion
For more information about the data that we collect, see [Optional diagnostic data from Intune Client apps](/mem/intune/protect/client-apps-optional-data).
```

2023-03-06 16:48 UTC, JohanFreelancer9 requested changes
Copy review.

2023-03-06 22:29 UTC, lenewsad commented
#sign-off

2023-03-07 09:18 UTC, JohanFreelancer9 approved these changes

2023-03-07 13:23 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-03-07 15:28 UTC, merged