Update resize-cloud-pc.md
MicrosoftDocs/memdocs pull request #3668
Opened 2023-03-10 14:53 UTC by BenMartinBaur

At the moment user data is just preserved if they are synced to OneDrive for Business.  Resizing a cloud pc without OfB will end in data loss.

2023-03-11 06:31 UTC, JohanFreelancer9 commented on windows-365/enterprise/resize-cloud-pc.md
> +When using OneDrive for Business, resizing preserves user data. Users will be able to access all of their data after the resizing is finished.
```suggestion
When using OneDrive, resizing preserves user data. Users will be able to access all of their data after the resizing is finished.
```

2023-03-11 06:31 UTC, JohanFreelancer9 requested changes
Copy review - @BenMartinBaur, kindly commit the suggested change. Many thanks.

2023-03-11 14:29 UTC, JohanFreelancer9 approved these changes

2023-03-17 22:14 UTC, ErikjeMS commented
Closing per PM response that change isn't accurate.

2023-03-17 22:14 UTC, closed without merging