Update enroll-device-android-company-portal.md
MicrosoftDocs/memdocs pull request #3675
Opened 2023-03-15 14:59 UTC by msbemba

Fixed the embedded video to display

Fixes#https://github.com/MicrosoftDocs/memdocs/issues/3663

2023-03-15 14:59 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-03-15 15:22 UTC, JohanFreelancer9 commented on memdocs/intune/user-help/enroll-device-android-company-portal.md
> +
```suggestion
```

2023-03-15 15:23 UTC, JohanFreelancer9 requested changes
Copy review.

2023-03-15 15:24 UTC, JohanFreelancer9 commented on memdocs/intune/user-help/enroll-device-android-company-portal.md
>  > protection outside of what native Android provides. To check if you have a Samsung Knox device,> go to **Settings** > **About device**. If you don't see **Knox version** listed there, you have a na
```suggestion
> protection outside of what native Android provides. To check if you have a Samsung Knox device, go to **Settings** > **About device**. If you don't see **Knox version** listed there, you have a native Android device.  
```

2023-03-16 00:01 UTC, lenewsad approved these changes

2023-03-16 00:01 UTC, lenewsad commented
#sign-off

2023-03-16 14:39 UTC, merged