Update help-desk-operators.md
MicrosoftDocs/memdocs pull request #3685
Opened 2023-03-20 18:52 UTC by mackie1604

Adding note for RBAC permission required to collect and access diagnostics in the troubleshooting blade

2023-03-20 19:17 UTC, Erikre commented
#sign-off

2023-03-21 06:38 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/help-desk-operators.md
> +> To collect and access diagnostics you must have the collect diagnostics permission added to your role, see [Role-based administration control (RBAC) with Intune](role-based-access-control.md)
```suggestion
> To collect and access diagnostics you must have the Collect diagnostics permission added to your role. For more information, see [Role-based administration control (RBAC) with Intune](role-based-access-control.md).
```

2023-03-21 06:39 UTC, JohanFreelancer9 requested changes
Copy review - @mackie1604, kindly commit the suggested changes. Many thanks.

2023-03-21 16:48 UTC, JohanFreelancer9 approved these changes

2023-03-23 17:36 UTC, Erikre commented
#sign-off

2023-03-23 17:36 UTC, merged