Update licenses-assign.md
MicrosoftDocs/memdocs pull request #3759
Opened 2023-04-06 16:03 UTC by msbemba

added more information about device licenses

Fixes https://github.com/MicrosoftDocs/memdocs/issues/3748

2023-04-06 16:03 UTC, msbemba commented
@JohanFreelancer9 PLease copy review

2023-04-07 12:17 UTC, yogkumgit commented
@JohanFreelancer9

2023-04-07 20:18 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/licenses-assign.md
> +- You can purchase licenses for any devices separately from user licenses. Device licenses do not need to be assigned to the devices. Each device that accesses and uses the online services and relate
```suggestion
- You can purchase licenses for any devices separately from user licenses. Device licenses do not need to be assigned to the devices. Each device that accesses and uses the online services and related software (including System Center software) must have a device license available in the Microsoft 365 tenant.
```

2023-04-07 20:18 UTC, JohanFreelancer9 requested changes
Copy review.

2023-04-08 14:34 UTC, JohanFreelancer9 approved these changes

2023-04-13 20:32 UTC, merged