Update app-sdk-ios.md
MicrosoftDocs/memdocs pull request #3800
Opened 2023-04-20 14:49 UTC by msbemba

Added a note that If the App Protection Policy is related to Managed Devices, it is necessary to create an App Configuration Profile of the application that has Intune integrated.

Fixes https://github.com/MicrosoftDocs/memdocs/issues/3776

2023-04-20 14:50 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-04-21 01:20 UTC, JohanFreelancer9 commented on memdocs/intune/developer/app-sdk-ios.md
>  > [!NOTE]
```suggestion
> If the app protection policy is related to managed devices, creating an app configuration profile of the application that has Intune integrated is also necessary.
>
```

2023-04-21 01:21 UTC, JohanFreelancer9 requested changes
Copy review.

2023-07-25 14:02 UTC, yogkumgit commented
@msbemba remove warnings.

2023-07-30 15:19 UTC, msbemba commented
@yogkumgit The warnings are for the Header in the document which I think only the Author can add.

Thanks
Sri

2023-07-31 11:43 UTC, yogkumgit commented
@Erikre Please review and signoff this PR. Thanks

2023-10-26 21:53 UTC, Erikre approved these changes

2023-10-26 21:53 UTC, Erikre commented
#sign-off

2023-10-26 21:55 UTC, Erikre approved these changes

2023-10-26 21:55 UTC, Erikre commented
#sign-off

2023-10-26 21:55 UTC, merged