Update how-to-enable.md
MicrosoftDocs/memdocs pull request #3804
Opened 2023-04-20 19:20 UTC by rededwin

Add link to Intune advanced deployment guide (FastTrack) that's available in M365 Admin Center

2023-04-21 05:09 UTC, JohanFreelancer9 commented on memdocs/configmgr/comanage/how-to-enable.md
> +> As a companion to this article, we recommend using the [Microsoft Intune Configuration Manager co-management setup guide](https://go.microsoft.com/fwlink/?linkid=2224782) when signed in to the Micr
```suggestion
> As a companion to this article, we recommend using the [Microsoft Intune Configuration Manager co-management setup guide](https://go.microsoft.com/fwlink/?linkid=2224782) when signed in to the Microsoft 365 admin center. This guide will customize your experience based on your environment.
```

2023-04-21 05:10 UTC, JohanFreelancer9 requested changes
Copy review - @rededwin, kindly commit the minor suggested change. Many thanks.

2023-04-21 15:22 UTC, rededwin commented
@gowdhamankarthikeyan PR has been copyedited and is ready for final review, could you kindly please check and merge? Thanks!

2023-04-22 05:09 UTC, JohanFreelancer9 approved these changes

2023-05-10 03:43 UTC, gowdhamankarthikeyan requested changes
Can you remove the "Microsoft Intune Configuration Manager" words and keep it simple as "co-management setup guide"?

2023-05-10 06:27 UTC, JohanFreelancer9 commented on memdocs/configmgr/comanage/how-to-enable.md
> +> As a companion to this article, we recommend using the [Microsoft Intune Configuration Manager co-management setup guide](https://go.microsoft.com/fwlink/?linkid=2224782) when signed in to the Micr
```suggestion
> As a companion to this article, we recommend using the [co-management setup guide](https://go.microsoft.com/fwlink/?linkid=2224782) when signed in to the Microsoft 365 admin center. This guide will customize your experience based on your environment.
```

2023-05-10 06:28 UTC, JohanFreelancer9 requested changes
@rededwin, Kindly commit the suggested change as per @gowdhamankarthikeyan's request. Many thanks.

2023-05-10 15:51 UTC, rededwin commented
@JohanFreelancer9 @gowdhamankarthikeyan please review and approve, thank you

2023-05-11 04:23 UTC, JohanFreelancer9 approved these changes

2023-05-14 23:05 UTC, rededwin commented
@JohanFreelancer9 @gowdhamankarthikeyan when will this be published to external?

2023-05-17 09:54 UTC, gowdhamankarthikeyan approved these changes
Approved.

2023-05-17 09:54 UTC, gowdhamankarthikeyan commented
#sign-off

2023-05-24 22:51 UTC, rededwin commented
@gowdhamankarthikeyan when will this be published externally?  Thank you

2023-05-25 15:31 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-05-25 20:54 UTC, merged

2023-05-25 21:22 UTC, tiburd commented
@rededwin 
Hi,

This pull request was opened in the public repo. PMs and content developers should work in the private repo, as described in [the authoring guide](https://review.docs.microsoft.com/en-us/Office-Authoring-Guide/office-docs-authoring-overview?branch=main). 

We reviewed and merged this PR but encourage you to use the private repo for future contributions to Microsoft Learn.

The changes in this PR will sync with the private repo and create a new sync PR; if that PR is reviewed and merged before the 3:30 PubOps publish to live, it should be live shortly after that. 

Thanks!

2023-05-25 21:23 UTC, rededwin commented
[like]  Edwin Der (HE/HIM/HIS) reacted to your message:
________________________________
From: Tina Burden ***@***.***>
Sent: Thursday, May 25, 2023 9:22:26 PM
To: MicrosoftDocs/memdocs ***@***.***>
Cc: Edwin Der (HE/HIM/HIS) ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/memdocs] Update how-to-enable.md (PR #3804)


@rededwin<https://github.com/rededwin>
Hi,

This pull request was opened in the public repo. PMs and content developers should work in the private repo, as described in the authoring guide<https://review.docs.microsoft.com/en-us/Office-Authoring-Guide/office-docs-authoring-overview?branch=main>.

We reviewed and merged this PR but encourage you to use the private repo for future contributions to Microsoft Learn.

The changes in this PR will sync with the private repo and create a new sync PR; if that PR is reviewed and merged before the 3:30 PubOps publish to live, it should be live shortly after that.

Thanks!

—
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/memdocs/pull/3804#issuecomment-1563521786>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6Z3KE5T7ZYFYQX4Z5PQCZLXH7ERFANCNFSM6AAAAAAXF5XQNY>.
You are receiving this because you were mentioned.Message ID: ***@***.***>