Update macos-shell-scripts.md
MicrosoftDocs/memdocs pull request #3814
Opened 2023-04-24 18:10 UTC by theneiljohnson

Added comment to highlight that scripts will run after a reboot if a frequency is set.

   - **Run script as signed-in user**: Select **Yes** to run the script with the user's credentials on the device. Choose **No** (default) to run the script as the root user.

2023-04-25 03:08 UTC, JohanFreelancer9 commented on memdocs/intune/apps/macos-shell-scripts.md
> +   - **Script frequency:** Select how often the script is to be run. Choose **Not configured** (default) to run a script only once. Scripts with a frequency set will also run after a device reboot.
```suggestion
   - **Script frequency:** Select how often the script is to be run. Choose **Not configured** (default) to run a script only once. Scripts with a frequency set will also run after a device restart.
```

2023-04-25 03:09 UTC, JohanFreelancer9 requested changes
Copy review - @theneiljohnson, kindly commit the suggested change. Many thanks.

2023-04-25 08:13 UTC, theneiljohnson commented
Added that scripts with a frequency set will also run on device restart.

2023-04-25 08:58 UTC, JohanFreelancer9 approved these changes

2023-07-25 13:59 UTC, yogkumgit commented
@Erikre Please review and sign off this PR. Thanks

2023-08-17 22:54 UTC, Erikre approved these changes

2023-08-17 22:55 UTC, Erikre commented
Thanks for the contribution! #sign-off

2023-08-17 22:55 UTC, Erikre commented
#sign-off

2023-08-17 22:55 UTC, merged