Update device-sync.md
MicrosoftDocs/memdocs pull request #3865
Opened 2023-05-10 11:56 UTC by PanuSaukko

I wanted to add a note that Sync is not needed for Android Enterprise devices.

2023-05-11 05:58 UTC, JohanFreelancer9 commented on memdocs/intune/remote-actions/device-sync.md
> +The **Sync** device action is not needed for Android Enterprise devices, because the devices will get new configurations/applications almost immediately after you have assigned them to Android Enterp
```suggestion
> [!NOTE]
> The **Sync** device action is not needed for Android Enterprise devices, because the devices will get new configurations and applications almost immediately after you have assigned them to Android Enterprise devices. 
```

2023-05-11 05:59 UTC, JohanFreelancer9 requested changes
Copy review - @PanuSaukko, kindly commit the suggested changes. Many thanks.

2023-06-20 20:47 UTC, Smritib17 commented
@JohanFreelancer9,  Device sync is currently not supported due to the architecture of the platform and should the platform support it, we would be open to extending this action to AE devices. Based on inputs from the PM this statement should not be added to the docs. You can close the issue. 
@msbemba @yogkumgit

2023-06-21 07:29 UTC, JohanFreelancer9 commented
> @JohanFreelancer9, Device sync is currently not supported due to the architecture of the platform and should the platform support it, we would be open to extending this action to AE devices. Based on inputs from the PM this statement should not be added to the docs. You can close the issue. @msbemba @yogkumgit

@yogkumgit @msbemba please close this PR as per the feedback. Thanks.

2023-06-21 15:49 UTC, closed without merging