Update collect-diagnostics.md
MicrosoftDocs/memdocs pull request #3866
Opened 2023-05-10 15:48 UTC by msbemba

Made changes to the navigation

Fixes https://github.com/MicrosoftDocs/memdocs/issues/3852

2023-05-10 15:48 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-05-11 04:21 UTC, JohanFreelancer9 commented on memdocs/intune/remote-actions/collect-diagnostics.md
> +4. Click on **Diagnostics**, select **Download**.
```suggestion
2. Navigate to **Devices** > **Windows Devices**.
3. Select a device.
4. Select **Diagnostics** > **Download**.
```

2023-05-11 04:21 UTC, JohanFreelancer9 requested changes
Copy review.

2023-05-11 08:28 UTC, JohanFreelancer9 approved these changes

2023-05-11 11:23 UTC, yogkumgit commented
@Brenduns Please review and signoff this PR. Thanks

2023-05-11 17:04 UTC, Brenduns commented
#sign-off    @yogkumgit

2023-05-12 14:27 UTC, merged