Update devices-wipe.md
MicrosoftDocs/memdocs pull request #3918
Opened 2023-06-01 06:39 UTC by msbemba

made changes to the navigation to Retire an Apple ADE device from Intune

Fixes https://github.com/MicrosoftDocs/memdocs/issues/3915

2023-06-01 06:39 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-06-01 09:43 UTC, JohanFreelancer9 commented on memdocs/intune/remote-actions/devices-wipe.md
> +4. Select the Device , choose **Release from Organization**.
```suggestion
4. Select the device and choose **Release from Organization**.
```

2023-06-01 09:43 UTC, JohanFreelancer9 commented on memdocs/intune/remote-actions/devices-wipe.md
> +5. Check **I understand this cannot be undone** and click on **Release**
```suggestion
5. Check **I understand this cannot be undone** and select **Release**.
```

2023-06-01 09:43 UTC, JohanFreelancer9 requested changes
Copy review.

2023-06-01 16:08 UTC, yogkumgit commented
@msbemba

2023-06-01 16:08 UTC, yogkumgit commented
@Smritib17 Please review and signoff this PR. Thanks

2023-06-07 15:53 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-06-07 16:23 UTC, tiburd commented on memdocs/intune/remote-actions/devices-wipe.md
> +4. Select the Device , choose **Release from Organization**.
```suggestion
4. Select the device, and then select **Release from Organization**.
```

2023-06-07 16:25 UTC, tiburd commented on memdocs/intune/remote-actions/devices-wipe.md
> +5. Check **I understand this cannot be undone** and click on **Release**
```suggestion
5. Check **I understand this cannot be undone**, and then select **Release**.
```

2023-06-07 16:25 UTC, merged