Update multi-factor-authentication.md
MicrosoftDocs/memdocs pull request #3961
Opened 2023-06-14 05:29 UTC by msbemba

Added info about TAP

Fixes https://github.com/MicrosoftDocs/memdocs/issues/3931

2023-06-14 05:30 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-06-14 09:05 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/multi-factor-authentication.md
> +> Or you can configure [Temporary Access Pass](/azure/active-directory/authentication/howto-authentication-temporary-access-pass)
```suggestion
> Alternatively, you can configure a [Temporary Access Pass](/azure/active-directory/authentication/howto-authentication-temporary-access-pass).
```

2023-06-14 09:06 UTC, JohanFreelancer9 requested changes
Copy review.

2023-06-14 14:11 UTC, JohanFreelancer9 approved these changes

2023-08-16 05:45 UTC, yogkumgit commented
@lenewsad Please update. Thanks

2023-08-16 18:17 UTC, lenewsad reviewed
Hi @msbemba, thanks for the edit. I can't confirm if this is something that device users can use as an alternative option to this policy, so no change to docs. If this is something that the product team identifies as an alternative in the future, we will be sure to add and expand upon it.

2023-08-17 13:50 UTC, closed without merging