Update windows-enrollment-status.md
MicrosoftDocs/memdocs pull request #4007
Opened 2023-07-05 06:07 UTC by sdabrai

Received feedback from customers that documentation makes it appear that default ESP profile will always win over user assigned ESP since it is assigned to "all devices" by default.

2023-07-06 08:21 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/windows-enrollment-status.md
> +1. Intune applies the highest-priority profile assigned to the device (exluding the default ESP profile).
```suggestion
1. Intune applies the highest-priority profile assigned to the device (excluding the default ESP profile). 
```

2023-07-06 08:21 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/windows-enrollment-status.md
> +2. If no profiles are targeted at the device (exluding the default ESP profile), Intune applies the highest-priority profile assigned to the user. This only works in scenarios where there is a user.
```suggestion
2. If no profiles are targeted at the device (excluding the default ESP profile), Intune applies the highest-priority profile assigned to the user. This only works in scenarios where there is a user. Only profiles targeted at devices can be applied in white glove and self-deploying scenarios.   
```

2023-07-06 08:22 UTC, JohanFreelancer9 requested changes
Copy review - @sdabrai, kindly commit the suggested changes. Many thanks.

2023-07-06 15:24 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/windows-enrollment-status.md
> +2. If no profiles are targeted at the device (excluding the default ESP profile), Intune applies the highest-priority profile assigned to the user. This only works in scenarios where there is a user.
```suggestion
2. If no profiles are targeted at the device (excluding the default ESP profile), Intune applies the highest-priority profile assigned to the user. This only works in scenarios where there is a user. Only profiles targeted at devices can be applied in pre-provisioning and self-deploying scenarios.   
```

2023-07-06 15:25 UTC, JohanFreelancer9 requested changes
Apologies @sdabrai, one more change, please. We do not use the term "white glove" in Microsoft documentation. Many thanks.

2023-07-07 04:56 UTC, JohanFreelancer9 approved these changes

2023-07-21 19:31 UTC, lenewsad commented
Hi @sdabrai, thanks for your contribution to the Microsoft Intune docs! A few build errors popped up so I incorporated your feedback in a new pull request. Changes will be live on our Learn website shortly.

2023-07-21 19:31 UTC, closed without merging

2023-07-21 21:33 UTC, sdabrai commented
[like]  Siddharth Dabrai reacted to your message:
________________________________
From: Laura Newsad ***@***.***>
Sent: Friday, July 21, 2023 7:32:09 PM
To: MicrosoftDocs/memdocs ***@***.***>
Cc: Siddharth Dabrai ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/memdocs] Update windows-enrollment-status.md (PR #4007)


Hi @sdabrai<https://github.com/sdabrai>, thanks for your contribution to the Microsoft Intune docs! A few build errors popped up so I incorporated your feedback in a new pull request. Changes will be live on our Learn website shortly.

—
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/memdocs/pull/4007#issuecomment-1646155149>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AUWED3XSSP53K5BFE4J4FE3XRLKLTANCNFSM6AAAAAAZ6OWNX4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>