Update app-approval.md to correct from internet section
MicrosoftDocs/memdocs pull request #4015
Opened 2023-07-07 17:04 UTC by umair0204

Corecting the App authentication section to and explicitly mentioning Client app.

2023-07-07 17:21 UTC, BalaDelli approved these changes

2023-07-08 04:39 UTC, JohanFreelancer9 commented on memdocs/configmgr/apps/deploy-use/app-approval.md
> +    1. Select the **Client** application that was created for Configuration Manager **Cloud Management** integration.
```suggestion
    1. Select the **Client** application created for Configuration Manager **Cloud Management** integration.
```

2023-07-08 04:40 UTC, JohanFreelancer9 requested changes
Copy review - @umair0204, kindly commit the minor suggested change. Many thanks.

2023-07-24 15:10 UTC, JohanFreelancer9 approved these changes

2023-07-26 19:13 UTC, umair0204 commented
When will the changes merge to main docs @JohanFreelancer9 ?

2023-10-27 15:37 UTC, BalaDelli approved these changes

2023-10-27 15:37 UTC, BalaDelli commented
#sign-off

2024-04-22 03:49 UTC, merged

2024-04-22 03:49 UTC, dougeby commented
fixed conflict. This was signed-off on but not merged. Merging.