Update automated-device-enrollment-authentication.md
MicrosoftDocs/memdocs pull request #4032
Opened 2023-07-13 13:35 UTC by msbemba

Added clarity to mention that  all features mentioned above are not supported in Apple setup Assistant authentication methods.

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4020

2023-07-13 15:27 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/automated-device-enrollment-authentication.md
> +All The features mentioned above aren't supported in Apple Setup Assistant authentication methods.
```suggestion
All of the features mentioned in Option 1 aren't supported in Apple Setup Assistant authentication methods. 
```

2023-07-13 15:27 UTC, JohanFreelancer9 requested changes
Copy review.

2023-07-14 05:54 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/automated-device-enrollment-authentication.md
> +All of the features mentioned in Option 1 aren't supported in Apple Setup Assistant authentication methods.
```suggestion
None of the features mentioned in Option 1 are supported in Apple Setup Assistant authentication methods. 
```

2023-07-14 05:54 UTC, JohanFreelancer9 requested changes
Apologies @msbemba, one more, please.

2023-07-14 07:26 UTC, JohanFreelancer9 approved these changes

2023-07-14 15:12 UTC, lenewsad approved these changes

2023-07-14 15:13 UTC, lenewsad commented
#sign-off

2023-07-17 17:57 UTC, merged