Update microsoft-intune-app-linux.md
MicrosoftDocs/memdocs pull request #4061
Opened 2023-07-24 17:37 UTC by msbemba

Added cmd to allow the Company Portal to read the disk encryption

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4040

2023-07-24 17:37 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-07-25 05:10 UTC, JohanFreelancer9 commented on memdocs/intune/user-help/microsoft-intune-app-linux.md
> +4. Run the following command to allow the Company Portal to read the disk encryption
```suggestion
4. Run the following command to allow the Company Portal to read the disk encryption:
```

2023-07-25 05:10 UTC, JohanFreelancer9 requested changes
Copy review.

2023-07-25 13:28 UTC, JohanFreelancer9 approved these changes

2023-07-25 13:49 UTC, yogkumgit commented
@lenewsad Please review and signoff this PR. Thanks

2023-07-25 17:45 UTC, lenewsad commented
Hi @msbemba @yogkumgit, thanks for making this change--asking PM to review.

2023-07-31 07:57 UTC, siimsoni commented
Hi,

please take a careful consideration prior to adding users to groups, as it can have security implications:

> The group disk can be very dangerous, since hard drives in /dev/sd* and /dev/hd* can be read and written bypassing any file system and any partition, allowing a normal user to disclose, alter and destroy both the partitions and the data of such drives without root privileges. Users should never belong to this group.

https://wiki.debian.org/SystemGroups

2023-11-09 15:10 UTC, Foorack requested changes

2023-11-09 15:10 UTC, Foorack commented on memdocs/intune/user-help/microsoft-intune-app-linux.md
> +    `$ sudo usermod -a -G disk <USER_ACCOUNT>`
I have **security concerns** regarding this change.

![image](https://github.com/MicrosoftDocs/memdocs/assets/5008081/fbf2eefc-26e3-48e8-a543-72a942babef7)

Recommending to add the local user to group `disk` is equivalent of giving that user SuperAdmin (root) access.

2023-11-29 20:02 UTC, lenewsad commented
Hi @msbemba, we can close this PR. I have been unable to get an answer from the product team that confirms this change is needed.

2023-12-01 05:18 UTC, closed without merging