Update remote-help.md
MicrosoftDocs/memdocs pull request #4064
Opened 2023-07-26 15:49 UTC by msbemba

Changed the wording to reduce ambiguity

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4025

2023-07-26 15:50 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-07-26 21:49 UTC, Smritib17 approved these changes

2023-07-26 21:50 UTC, Smritib17 commented
#sign-off

2023-07-27 06:59 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/remote-help.md
> +- The helper must be signed-in on an Intune Enrolled Device.
```suggestion
- The helper must be signed in on an Intune enrolled device.
```

2023-07-27 06:59 UTC, JohanFreelancer9 requested changes
Copy review.

2023-07-27 12:15 UTC, yogkumgit commented
@msbemba

2023-07-27 14:33 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-07-27 16:31 UTC, merged