Update profiles.md
MicrosoftDocs/memdocs pull request #4144
Opened 2023-08-31 20:11 UTC by mosoto07

Added a note regarding the assignation to All devices + Exclusions. This was confirmed by PG: https://portal.microsofticm.com/imp/v3/incidents/incident/413452483/summary

2023-09-02 07:21 UTC, JohanFreelancer9 commented on autopilot/profiles.md
> +> If you use the assigment **All Devices** exclusions are not supported. Any workaround to excluse groups while targeting it to all devices may cause assignation problems and require to re-upload the
```suggestion
> If you use the assignment **All Devices**, exclusions are not supported. Any workaround to exclude groups while targeting it to all devices may cause assignation problems and requires uploading the hash again.
```

2023-09-02 07:21 UTC, JohanFreelancer9 requested changes
Copy review - @mosoto07, kindly commit the suggested changes. Many thanks.

2023-09-06 02:47 UTC, JohanFreelancer9 approved these changes

2023-09-06 18:51 UTC, frankroj commented
#sign-off

2023-09-06 18:51 UTC, merged