Update app-wrapper-prepare-ios.md for -ac and -ar to be required params
MicrosoftDocs/memdocs pull request #4182
Opened 2023-09-11 17:37 UTC by tranamst

Update app-wrapper-prepare-ios.md for -ac and -ar to be required params

2023-09-12 03:17 UTC, JohanFreelancer9 commented on memdocs/intune/developer/app-wrapper-prepare-ios.md
> +|**-ac**|`<Client ID of the input app if the app uses the Microsoft Authentication Library>` This is the guid in the Client ID field from your app's listing in the App Registration blade. |
```suggestion
|**-ac**|`<Client ID of the input app if the app uses the Microsoft Authentication Library>` This is the GUID in the Client ID field from your app's listing in the App Registration blade. |
```

2023-09-12 03:18 UTC, JohanFreelancer9 requested changes
Copy review - @tranamst, kindly commit the suggested change. Many thanks.

2023-09-12 15:46 UTC, tranamst commented
> Copy review - @tranamst, kindly commit the suggested change. Many thanks.

Thanks for reviewing. I have updated PR with the suggested change. Could you merge this in? Thanks!

2023-09-13 09:59 UTC, JohanFreelancer9 approved these changes
@tranamst, I only do a copy edit. The author or manager will merge it once the changes are approved. Thanks!

2023-09-18 15:33 UTC, tranamst commented
@Erikre Bumping this - Could you take a look and approve? Thank you!

2023-09-26 19:41 UTC, tranamst commented
@JohanFreelancer9 Could you help me ping someone on the reviewer team to approve this for me? Thank you.

2023-09-27 06:11 UTC, JohanFreelancer9 commented
> @JohanFreelancer9 Could you help me ping someone on the reviewer team to approve this for me? Thank you.

@yogkumgit, could you possibly assist? Many thanks.

2023-09-27 10:59 UTC, yogkumgit commented
@Erikre Please review and sign off this PR. Thanks

2023-10-09 16:04 UTC, tranamst commented
@yogkumgit Can you review and sign this PR off? It has been 3 weeks.

2023-10-10 11:57 UTC, yogkumgit commented
@Erikre Gentle reminder. Thanks

2023-10-11 19:44 UTC, Erikre approved these changes

2023-10-11 19:44 UTC, Erikre commented
#sign-off

2023-10-11 19:45 UTC, merged