Update advanced-threat-protection-configure.md
MicrosoftDocs/memdocs pull request #4203
Opened 2023-09-15 13:59 UTC by msbemba

Added an example of Classic conditional access policies

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4196

2023-09-15 13:59 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-09-15 16:08 UTC, JohanFreelancer9 commented on memdocs/intune/protect/advanced-threat-protection-configure.md
> +> When you integrate a new application to Intune Mobile Threat Defense and enable the connection to Intune, Intune creates a classic conditional access policy such as "[Windows Defender ATP] Device p
```suggestion
> When you integrate a new application to Intune Mobile Threat Defense and enable the connection to Intune, Intune creates a classic conditional access policy, such as Windows Defender ATP device policy, in Azure Active Directory. Each MTD app you integrate, including [Microsoft Defender for Endpoint](advanced-threat-protection.md) or any of our additional [MTD partners](mobile-threat-defense.md#mobile-threat-defense-partners), creates a new classic conditional access policy. These policies can be ignored, but should not be edited, deleted, or disabled.
```

2023-09-15 16:08 UTC, JohanFreelancer9 approved these changes
Copy review.

2023-09-18 11:33 UTC, yogkumgit commented
@msbemba

2023-09-18 13:26 UTC, JohanFreelancer9 requested changes
Copy review.

2023-09-19 07:30 UTC, JohanFreelancer9 approved these changes

2023-09-19 14:23 UTC, Brenduns commented
#sign-off

2023-09-19 14:52 UTC, merged