Update certificate-connector-install.md
MicrosoftDocs/memdocs pull request #4261
Opened 2023-10-04 07:56 UTC by msbemba

Updated the sentence for the intune license requirement as it creates ambiguity.

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4239

2023-10-04 07:56 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-10-04 08:43 UTC, JohanFreelancer9 commented on memdocs/intune/protect/certificate-connector-install.md
> +6. On the *Azure AD Sign In* page, select the environment that hosts your Azure Active Directory, and then select **Sign In**. You’ll then be asked to authenticate your access. An Intune license is r
```suggestion
6. On the *Azure AD Sign In* page, select the environment that hosts your Azure Active Directory, and then select **Sign In**. You’ll then be asked to authenticate your access. An Intune license is required for the account that you sign in with which can be either a Global Administrator or an Intune Administrator.
```

2023-10-04 08:43 UTC, JohanFreelancer9 requested changes
Copy review.

2023-10-04 09:14 UTC, JohanFreelancer9 approved these changes

2023-10-04 13:40 UTC, yogkumgit commented
@lenewsad Please review and signoff this PR.  Thanks

2023-10-04 15:10 UTC, lenewsad approved these changes

2023-10-04 15:10 UTC, lenewsad commented
#sign-off

2023-10-05 09:16 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-10-05 15:18 UTC, merged