Update configuration-manager-faq.yml
MicrosoftDocs/memdocs pull request #4266
Opened 2023-10-04 15:38 UTC by baardhermansen

Added missing parenthesis in link to Autopilot information. Added info regarding Desktop analytics.
Added link to Endpoint analytics.

2023-10-05 06:29 UTC, JohanFreelancer9 commented on memdocs/configmgr/core/understand/configuration-manager-faq.yml
> +            - NOTE: Desktop Analytics is deprecated. See instead [Endpoint analytics](../../../analytics/index.yml)
```suggestion
            - NOTE: Desktop Analytics is deprecated. Instead, see [Endpoint analytics](../../../analytics/index.yml)
```

2023-10-05 06:30 UTC, JohanFreelancer9 requested changes
Copy review - @baardhermansen, kindly commit the minor suggested change. Many thanks.

2023-10-06 01:49 UTC, JohanFreelancer9 approved these changes

2023-10-06 04:41 UTC, Banreet approved these changes

2023-10-06 04:41 UTC, Banreet commented
#sign-off

2024-04-22 03:36 UTC, merged