Update whats-new.md
MicrosoftDocs/memdocs pull request #4374
Opened 2023-11-06 17:33 UTC by msbemba

Updated the steps for import and export settings catalog policies

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4358

2023-11-06 17:34 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-11-07 05:39 UTC, JohanFreelancer9 approved these changes

2023-11-07 15:02 UTC, yogkumgit commented
@Brenduns Please review and sign off this PR. Thanks

2023-11-07 16:03 UTC, Brenduns commented
#sign-off

2023-11-07 22:05 UTC, Brenduns approved these changes

2023-11-08 14:07 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-11-08 14:58 UTC, JohanFreelancer9 commented on memdocs/intune/fundamentals/whats-new.md
> +The Intune [settings catalog](../configuration/settings-catalog.md) lists all the settings you can configure, and all in one place (**Devices** > **Configuration profiles** > **Create** > **New Polic
```suggestion
The Intune [settings catalog](../configuration/settings-catalog.md) lists all the settings you can configure, and all in one place (**Devices** > **Configuration profiles** > **Create** > **New Policy** > Select your **platform** > For **Profile**, select **Settings catalog**).
```

2023-11-08 14:59 UTC, JohanFreelancer9 requested changes
Apologies @msbemba, one more, please.

2023-11-08 15:27 UTC, merged