Added http://localhost to redirect URI
MicrosoftDocs/memdocs pull request #4426
Opened 2023-12-04 19:32 UTC by jonasatgit

Added http://localhost to redirect URI and changed button

2023-12-05 04:19 UTC, JohanFreelancer9 commented on memdocs/configmgr/core/clients/manage/cmg/manually-register-azure-ad-apps.md
> +    - **Redirect URI**: Select: **Public client/native (mobile &desktop)** and type **http://localhost** as URI
```suggestion
    - **Redirect URI**: Select: **Public client/native (mobile & desktop)** and enter **http://localhost** as URI.
```

2023-12-05 04:19 UTC, JohanFreelancer9 requested changes
Copy review - @jonasatgit, kindly commit the suggested change. Many thanks.

2023-12-06 17:59 UTC, BalaDelli approved these changes

2024-04-22 03:30 UTC, dougeby commented
This was signed-off on but not merged. Merging.  #sign-off

2024-04-22 03:30 UTC, merged