Intune - Update windows-10-expedite-updates.md
MicrosoftDocs/memdocs pull request #4432
Opened 2023-12-05 20:51 UTC by unicornpancakes

Grammatical changes and various rewordings to make the document more legible.  Does not materially impact the message being communicated, these were just tense and grammatical errors that I think should be corrected.

2023-12-05 20:55 UTC, Smritib17 approved these changes

2023-12-06 06:36 UTC, JohanFreelancer9 commented on memdocs/intune/protect/windows-10-expedite-updates.md
> +Expedited update policies temporarily override deferrals and other settings to install updates as quickly as possible. This process enables devices to start the download and install of an expedited u
```suggestion
Expedited update policies temporarily override deferrals and other settings to install updates as quickly as possible. This process enables devices to start the download and installation of an expedited update without having to wait for the device to check in for updates.
```

2023-12-06 06:37 UTC, JohanFreelancer9 requested changes
Copy review - @unicornpancakes, kindly commit the additional suggested change. Many thanks.

2023-12-06 14:53 UTC, unicornpancakes commented
> Copy review - @unicornpancakes, kindly commit the additional suggested change. Many thanks.

Thanks for the feedback. Commit the change.

2023-12-07 04:28 UTC, JohanFreelancer9 approved these changes

2023-12-11 17:13 UTC, Smritib17 commented
#sign-off

2023-12-13 22:22 UTC, merged