Update web-based-device-enrollment-ios.md
MicrosoftDocs/memdocs pull request #4442
Opened 2023-12-11 10:40 UTC by msbemba

Made changes to step8 in step 2

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4412

2023-12-11 10:40 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-12-11 13:30 UTC, JohanFreelancer9 commented on memdocs/intune/enrollment/web-based-device-enrollment-ios.md
> +8. On the **Assignments** page, assign the profile to all Users or a group of users.
```suggestion
8. On the **Assignments** page, assign the profile to all users or a group of users.
```

2023-12-11 13:31 UTC, JohanFreelancer9 requested changes
Copy review.

2023-12-11 16:44 UTC, yogkumgit commented
@msbemba

2023-12-12 05:07 UTC, yogkumgit commented
@lenewsad Please review and signoff this PR. Thanks

2023-12-12 12:30 UTC, JohanFreelancer9 approved these changes

2023-12-14 13:58 UTC, lenewsad commented
Hi @msbemba @yogkumgit, in review with the product team.

2023-12-14 16:01 UTC, lenewsad approved these changes

2023-12-14 16:01 UTC, lenewsad commented
#sign-off

2023-12-15 04:53 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-12-15 14:08 UTC, merged